"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SHOW_FIELD_NUMBER: _builtins.int
    DEST_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    XVER_FIELD_NUMBER: _builtins.int
    SERVER_NAMES_FIELD_NUMBER: _builtins.int
    PRIVATE_KEY_FIELD_NUMBER: _builtins.int
    MIN_CLIENT_VER_FIELD_NUMBER: _builtins.int
    MAX_CLIENT_VER_FIELD_NUMBER: _builtins.int
    MAX_TIME_DIFF_FIELD_NUMBER: _builtins.int
    SHORT_IDS_FIELD_NUMBER: _builtins.int
    MLDSA65_SEED_FIELD_NUMBER: _builtins.int
    LIMIT_FALLBACK_UPLOAD_FIELD_NUMBER: _builtins.int
    LIMIT_FALLBACK_DOWNLOAD_FIELD_NUMBER: _builtins.int
    FINGERPRINT_FIELD_NUMBER: _builtins.int
    SERVER_NAME_FIELD_NUMBER: _builtins.int
    PUBLIC_KEY_FIELD_NUMBER: _builtins.int
    SHORT_ID_FIELD_NUMBER: _builtins.int
    MLDSA65_VERIFY_FIELD_NUMBER: _builtins.int
    SPIDER_X_FIELD_NUMBER: _builtins.int
    SPIDER_Y_FIELD_NUMBER: _builtins.int
    MASTER_KEY_LOG_FIELD_NUMBER: _builtins.int
    show: _builtins.bool
    dest: _builtins.str
    type: _builtins.str
    xver: _builtins.int
    private_key: _builtins.bytes
    min_client_ver: _builtins.bytes
    max_client_ver: _builtins.bytes
    max_time_diff: _builtins.int
    mldsa65_seed: _builtins.bytes
    Fingerprint: _builtins.str
    server_name: _builtins.str
    public_key: _builtins.bytes
    short_id: _builtins.bytes
    mldsa65_verify: _builtins.bytes
    spider_x: _builtins.str
    master_key_log: _builtins.str
    @_builtins.property
    def server_names(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def short_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
    @_builtins.property
    def limit_fallback_upload(self) -> Global___LimitFallback: ...
    @_builtins.property
    def limit_fallback_download(self) -> Global___LimitFallback: ...
    @_builtins.property
    def spider_y(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        show: _builtins.bool = ...,
        dest: _builtins.str = ...,
        type: _builtins.str = ...,
        xver: _builtins.int = ...,
        server_names: _abc.Iterable[_builtins.str] | None = ...,
        private_key: _builtins.bytes = ...,
        min_client_ver: _builtins.bytes = ...,
        max_client_ver: _builtins.bytes = ...,
        max_time_diff: _builtins.int = ...,
        short_ids: _abc.Iterable[_builtins.bytes] | None = ...,
        mldsa65_seed: _builtins.bytes = ...,
        limit_fallback_upload: Global___LimitFallback | None = ...,
        limit_fallback_download: Global___LimitFallback | None = ...,
        Fingerprint: _builtins.str = ...,
        server_name: _builtins.str = ...,
        public_key: _builtins.bytes = ...,
        short_id: _builtins.bytes = ...,
        mldsa65_verify: _builtins.bytes = ...,
        spider_x: _builtins.str = ...,
        spider_y: _abc.Iterable[_builtins.int] | None = ...,
        master_key_log: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["limit_fallback_download", b"limit_fallback_download", "limit_fallback_upload", b"limit_fallback_upload"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["Fingerprint", b"Fingerprint", "dest", b"dest", "limit_fallback_download", b"limit_fallback_download", "limit_fallback_upload", b"limit_fallback_upload", "master_key_log", b"master_key_log", "max_client_ver", b"max_client_ver", "max_time_diff", b"max_time_diff", "min_client_ver", b"min_client_ver", "mldsa65_seed", b"mldsa65_seed", "mldsa65_verify", b"mldsa65_verify", "private_key", b"private_key", "public_key", b"public_key", "server_name", b"server_name", "server_names", b"server_names", "short_id", b"short_id", "short_ids", b"short_ids", "show", b"show", "spider_x", b"spider_x", "spider_y", b"spider_y", "type", b"type", "xver", b"xver"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015

@_typing.final
class LimitFallback(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AFTER_BYTES_FIELD_NUMBER: _builtins.int
    BYTES_PER_SEC_FIELD_NUMBER: _builtins.int
    BURST_BYTES_PER_SEC_FIELD_NUMBER: _builtins.int
    after_bytes: _builtins.int
    bytes_per_sec: _builtins.int
    burst_bytes_per_sec: _builtins.int
    def __init__(
        self,
        *,
        after_bytes: _builtins.int = ...,
        bytes_per_sec: _builtins.int = ...,
        burst_bytes_per_sec: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["after_bytes", b"after_bytes", "burst_bytes_per_sec", b"burst_bytes_per_sec", "bytes_per_sec", b"bytes_per_sec"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LimitFallback: _TypeAlias = LimitFallback  # noqa: Y015
