"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class TCPItem(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DELAY_MIN_FIELD_NUMBER: _builtins.int
    DELAY_MAX_FIELD_NUMBER: _builtins.int
    RAND_FIELD_NUMBER: _builtins.int
    RAND_MIN_FIELD_NUMBER: _builtins.int
    RAND_MAX_FIELD_NUMBER: _builtins.int
    PACKET_FIELD_NUMBER: _builtins.int
    delay_min: _builtins.int
    delay_max: _builtins.int
    rand: _builtins.int
    rand_min: _builtins.int
    rand_max: _builtins.int
    packet: _builtins.bytes
    def __init__(
        self,
        *,
        delay_min: _builtins.int = ...,
        delay_max: _builtins.int = ...,
        rand: _builtins.int = ...,
        rand_min: _builtins.int = ...,
        rand_max: _builtins.int = ...,
        packet: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["delay_max", b"delay_max", "delay_min", b"delay_min", "packet", b"packet", "rand", b"rand", "rand_max", b"rand_max", "rand_min", b"rand_min"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TCPItem: _TypeAlias = TCPItem  # noqa: Y015

@_typing.final
class TCPSequence(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SEQUENCE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def sequence(self) -> _containers.RepeatedCompositeFieldContainer[Global___TCPItem]: ...
    def __init__(
        self,
        *,
        sequence: _abc.Iterable[Global___TCPItem] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sequence", b"sequence"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TCPSequence: _TypeAlias = TCPSequence  # noqa: Y015

@_typing.final
class TCPConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLIENTS_FIELD_NUMBER: _builtins.int
    SERVERS_FIELD_NUMBER: _builtins.int
    ERRORS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def clients(self) -> _containers.RepeatedCompositeFieldContainer[Global___TCPSequence]: ...
    @_builtins.property
    def servers(self) -> _containers.RepeatedCompositeFieldContainer[Global___TCPSequence]: ...
    @_builtins.property
    def errors(self) -> _containers.RepeatedCompositeFieldContainer[Global___TCPSequence]: ...
    def __init__(
        self,
        *,
        clients: _abc.Iterable[Global___TCPSequence] | None = ...,
        servers: _abc.Iterable[Global___TCPSequence] | None = ...,
        errors: _abc.Iterable[Global___TCPSequence] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["clients", b"clients", "errors", b"errors", "servers", b"servers"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TCPConfig: _TypeAlias = TCPConfig  # noqa: Y015

@_typing.final
class UDPItem(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RAND_FIELD_NUMBER: _builtins.int
    RAND_MIN_FIELD_NUMBER: _builtins.int
    RAND_MAX_FIELD_NUMBER: _builtins.int
    PACKET_FIELD_NUMBER: _builtins.int
    rand: _builtins.int
    rand_min: _builtins.int
    rand_max: _builtins.int
    packet: _builtins.bytes
    def __init__(
        self,
        *,
        rand: _builtins.int = ...,
        rand_min: _builtins.int = ...,
        rand_max: _builtins.int = ...,
        packet: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["packet", b"packet", "rand", b"rand", "rand_max", b"rand_max", "rand_min", b"rand_min"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UDPItem: _TypeAlias = UDPItem  # noqa: Y015

@_typing.final
class UDPConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_FIELD_NUMBER: _builtins.int
    SERVER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def client(self) -> _containers.RepeatedCompositeFieldContainer[Global___UDPItem]: ...
    @_builtins.property
    def server(self) -> _containers.RepeatedCompositeFieldContainer[Global___UDPItem]: ...
    def __init__(
        self,
        *,
        client: _abc.Iterable[Global___UDPItem] | None = ...,
        server: _abc.Iterable[Global___UDPItem] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client", b"client", "server", b"server"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UDPConfig: _TypeAlias = UDPConfig  # noqa: Y015
