# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/finalmask/header/custom/config.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'transport/internet/finalmask/header/custom/config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7transport/internet/finalmask/header/custom/config.proto\x12/xray.transport.internet.finalmask.header.custom\"q\n\x07TCPItem\x12\x11\n\tdelay_min\x18\x01 \x01(\x03\x12\x11\n\tdelay_max\x18\x02 \x01(\x03\x12\x0c\n\x04rand\x18\x03 \x01(\x05\x12\x10\n\x08rand_min\x18\x04 \x01(\x05\x12\x10\n\x08rand_max\x18\x05 \x01(\x05\x12\x0e\n\x06packet\x18\x06 \x01(\x0c\"Y\n\x0bTCPSequence\x12J\n\x08sequence\x18\x01 \x03(\x0b\x32\x38.xray.transport.internet.finalmask.header.custom.TCPItem\"\xf7\x01\n\tTCPConfig\x12M\n\x07\x63lients\x18\x01 \x03(\x0b\x32<.xray.transport.internet.finalmask.header.custom.TCPSequence\x12M\n\x07servers\x18\x02 \x03(\x0b\x32<.xray.transport.internet.finalmask.header.custom.TCPSequence\x12L\n\x06\x65rrors\x18\x03 \x03(\x0b\x32<.xray.transport.internet.finalmask.header.custom.TCPSequence\"K\n\x07UDPItem\x12\x0c\n\x04rand\x18\x01 \x01(\x05\x12\x10\n\x08rand_min\x18\x02 \x01(\x05\x12\x10\n\x08rand_max\x18\x03 \x01(\x05\x12\x0e\n\x06packet\x18\x04 \x01(\x0c\"\x9f\x01\n\tUDPConfig\x12H\n\x06\x63lient\x18\x01 \x03(\x0b\x32\x38.xray.transport.internet.finalmask.header.custom.UDPItem\x12H\n\x06server\x18\x02 \x03(\x0b\x32\x38.xray.transport.internet.finalmask.header.custom.UDPItemB\xaf\x01\n3com.xray.transport.internet.finalmask.header.customP\x01ZDgithub.com/xtls/xray-core/transport/internet/finalmask/header/custom\xaa\x02/Xray.Transport.Internet.Finalmask.Header.Customb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.finalmask.header.custom.config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n3com.xray.transport.internet.finalmask.header.customP\001ZDgithub.com/xtls/xray-core/transport/internet/finalmask/header/custom\252\002/Xray.Transport.Internet.Finalmask.Header.Custom'
  _globals['_TCPITEM']._serialized_start=108
  _globals['_TCPITEM']._serialized_end=221
  _globals['_TCPSEQUENCE']._serialized_start=223
  _globals['_TCPSEQUENCE']._serialized_end=312
  _globals['_TCPCONFIG']._serialized_start=315
  _globals['_TCPCONFIG']._serialized_end=562
  _globals['_UDPITEM']._serialized_start=564
  _globals['_UDPITEM']._serialized_end=639
  _globals['_UDPCONFIG']._serialized_start=642
  _globals['_UDPCONFIG']._serialized_end=801
# @@protoc_insertion_point(module_scope)
