"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from app.log.command import config_pb2 as _config_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class LoggerServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> LoggerServiceAsyncStub: ...
    RestartLogger: _grpc.UnaryUnaryMultiCallable[_config_pb2.RestartLoggerRequest, _config_pb2.RestartLoggerResponse]

@_typing.type_check_only
class LoggerServiceAsyncStub(LoggerServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    RestartLogger: _aio.UnaryUnaryMultiCallable[_config_pb2.RestartLoggerRequest, _config_pb2.RestartLoggerResponse]  # type: ignore[assignment]

class LoggerServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def RestartLogger(
        self,
        request: _config_pb2.RestartLoggerRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_config_pb2.RestartLoggerResponse, _abc.Awaitable[_config_pb2.RestartLoggerResponse]]: ...

def add_LoggerServiceServicer_to_server(servicer: LoggerServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
