"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CORE_VERSION_FIELD_NUMBER: _builtins.int
    MIN_VERSION_FIELD_NUMBER: _builtins.int
    MAX_VERSION_FIELD_NUMBER: _builtins.int
    core_version: _builtins.str
    min_version: _builtins.str
    max_version: _builtins.str
    def __init__(
        self,
        *,
        core_version: _builtins.str = ...,
        min_version: _builtins.str = ...,
        max_version: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["core_version", b"core_version", "max_version", b"max_version", "min_version", b"min_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
