"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from app.observatory.command import command_pb2 as _command_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ObservatoryServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ObservatoryServiceAsyncStub: ...
    GetOutboundStatus: _grpc.UnaryUnaryMultiCallable[_command_pb2.GetOutboundStatusRequest, _command_pb2.GetOutboundStatusResponse]

@_typing.type_check_only
class ObservatoryServiceAsyncStub(ObservatoryServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    GetOutboundStatus: _aio.UnaryUnaryMultiCallable[_command_pb2.GetOutboundStatusRequest, _command_pb2.GetOutboundStatusResponse]  # type: ignore[assignment]

class ObservatoryServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def GetOutboundStatus(
        self,
        request: _command_pb2.GetOutboundStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.GetOutboundStatusResponse, _abc.Awaitable[_command_pb2.GetOutboundStatusResponse]]: ...

def add_ObservatoryServiceServicer_to_server(servicer: ObservatoryServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
