"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from common.net import address_pb2 as _address_pb2
from common.serial import typed_message_pb2 as _typed_message_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _DomainStrategy:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _DomainStrategyEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_DomainStrategy.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    AS_IS: _DomainStrategy.ValueType  # 0
    USE_IP: _DomainStrategy.ValueType  # 1
    USE_IP4: _DomainStrategy.ValueType  # 2
    USE_IP6: _DomainStrategy.ValueType  # 3
    USE_IP46: _DomainStrategy.ValueType  # 4
    USE_IP64: _DomainStrategy.ValueType  # 5
    FORCE_IP: _DomainStrategy.ValueType  # 6
    FORCE_IP4: _DomainStrategy.ValueType  # 7
    FORCE_IP6: _DomainStrategy.ValueType  # 8
    FORCE_IP46: _DomainStrategy.ValueType  # 9
    FORCE_IP64: _DomainStrategy.ValueType  # 10

class DomainStrategy(_DomainStrategy, metaclass=_DomainStrategyEnumTypeWrapper): ...

AS_IS: DomainStrategy.ValueType  # 0
USE_IP: DomainStrategy.ValueType  # 1
USE_IP4: DomainStrategy.ValueType  # 2
USE_IP6: DomainStrategy.ValueType  # 3
USE_IP46: DomainStrategy.ValueType  # 4
USE_IP64: DomainStrategy.ValueType  # 5
FORCE_IP: DomainStrategy.ValueType  # 6
FORCE_IP4: DomainStrategy.ValueType  # 7
FORCE_IP6: DomainStrategy.ValueType  # 8
FORCE_IP46: DomainStrategy.ValueType  # 9
FORCE_IP64: DomainStrategy.ValueType  # 10
Global___DomainStrategy: _TypeAlias = DomainStrategy  # noqa: Y015

class _AddressPortStrategy:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _AddressPortStrategyEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_AddressPortStrategy.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SrvPortOnly: _AddressPortStrategy.ValueType  # 1
    SrvAddressOnly: _AddressPortStrategy.ValueType  # 2
    SrvPortAndAddress: _AddressPortStrategy.ValueType  # 3
    TxtPortOnly: _AddressPortStrategy.ValueType  # 4
    TxtAddressOnly: _AddressPortStrategy.ValueType  # 5
    TxtPortAndAddress: _AddressPortStrategy.ValueType  # 6

class AddressPortStrategy(_AddressPortStrategy, metaclass=_AddressPortStrategyEnumTypeWrapper): ...

SrvPortOnly: AddressPortStrategy.ValueType  # 1
SrvAddressOnly: AddressPortStrategy.ValueType  # 2
SrvPortAndAddress: AddressPortStrategy.ValueType  # 3
TxtPortOnly: AddressPortStrategy.ValueType  # 4
TxtAddressOnly: AddressPortStrategy.ValueType  # 5
TxtPortAndAddress: AddressPortStrategy.ValueType  # 6
Global___AddressPortStrategy: _TypeAlias = AddressPortStrategy  # noqa: Y015

@_typing.final
class TransportConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROTOCOL_NAME_FIELD_NUMBER: _builtins.int
    SETTINGS_FIELD_NUMBER: _builtins.int
    protocol_name: _builtins.str
    """Transport protocol name."""
    @_builtins.property
    def settings(self) -> _typed_message_pb2.TypedMessage:
        """Specific transport protocol settings."""

    def __init__(
        self,
        *,
        protocol_name: _builtins.str = ...,
        settings: _typed_message_pb2.TypedMessage | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["settings", b"settings"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["protocol_name", b"protocol_name", "settings", b"settings"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TransportConfig: _TypeAlias = TransportConfig  # noqa: Y015

@_typing.final
class StreamConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: _builtins.int
    PORT_FIELD_NUMBER: _builtins.int
    PROTOCOL_NAME_FIELD_NUMBER: _builtins.int
    TRANSPORT_SETTINGS_FIELD_NUMBER: _builtins.int
    SECURITY_TYPE_FIELD_NUMBER: _builtins.int
    SECURITY_SETTINGS_FIELD_NUMBER: _builtins.int
    UDPMASKS_FIELD_NUMBER: _builtins.int
    TCPMASKS_FIELD_NUMBER: _builtins.int
    QUIC_PARAMS_FIELD_NUMBER: _builtins.int
    SOCKET_SETTINGS_FIELD_NUMBER: _builtins.int
    port: _builtins.int
    protocol_name: _builtins.str
    """Effective network."""
    security_type: _builtins.str
    """Type of security. Must be a message name of the settings proto."""
    @_builtins.property
    def address(self) -> _address_pb2.IPOrDomain: ...
    @_builtins.property
    def transport_settings(self) -> _containers.RepeatedCompositeFieldContainer[Global___TransportConfig]: ...
    @_builtins.property
    def security_settings(self) -> _containers.RepeatedCompositeFieldContainer[_typed_message_pb2.TypedMessage]:
        """Transport security settings. They can be either TLS or REALITY."""

    @_builtins.property
    def udpmasks(self) -> _containers.RepeatedCompositeFieldContainer[_typed_message_pb2.TypedMessage]: ...
    @_builtins.property
    def tcpmasks(self) -> _containers.RepeatedCompositeFieldContainer[_typed_message_pb2.TypedMessage]: ...
    @_builtins.property
    def quic_params(self) -> Global___QuicParams: ...
    @_builtins.property
    def socket_settings(self) -> Global___SocketConfig: ...
    def __init__(
        self,
        *,
        address: _address_pb2.IPOrDomain | None = ...,
        port: _builtins.int = ...,
        protocol_name: _builtins.str = ...,
        transport_settings: _abc.Iterable[Global___TransportConfig] | None = ...,
        security_type: _builtins.str = ...,
        security_settings: _abc.Iterable[_typed_message_pb2.TypedMessage] | None = ...,
        udpmasks: _abc.Iterable[_typed_message_pb2.TypedMessage] | None = ...,
        tcpmasks: _abc.Iterable[_typed_message_pb2.TypedMessage] | None = ...,
        quic_params: Global___QuicParams | None = ...,
        socket_settings: Global___SocketConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "quic_params", b"quic_params", "socket_settings", b"socket_settings"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "port", b"port", "protocol_name", b"protocol_name", "quic_params", b"quic_params", "security_settings", b"security_settings", "security_type", b"security_type", "socket_settings", b"socket_settings", "tcpmasks", b"tcpmasks", "transport_settings", b"transport_settings", "udpmasks", b"udpmasks"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StreamConfig: _TypeAlias = StreamConfig  # noqa: Y015

@_typing.final
class UdpHop(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PORTS_FIELD_NUMBER: _builtins.int
    INTERVAL_MIN_FIELD_NUMBER: _builtins.int
    INTERVAL_MAX_FIELD_NUMBER: _builtins.int
    interval_min: _builtins.int
    interval_max: _builtins.int
    @_builtins.property
    def ports(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        ports: _abc.Iterable[_builtins.int] | None = ...,
        interval_min: _builtins.int = ...,
        interval_max: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["interval_max", b"interval_max", "interval_min", b"interval_min", "ports", b"ports"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UdpHop: _TypeAlias = UdpHop  # noqa: Y015

@_typing.final
class QuicParams(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONGESTION_FIELD_NUMBER: _builtins.int
    BRUTAL_UP_FIELD_NUMBER: _builtins.int
    BRUTAL_DOWN_FIELD_NUMBER: _builtins.int
    UDP_HOP_FIELD_NUMBER: _builtins.int
    INIT_STREAM_RECEIVE_WINDOW_FIELD_NUMBER: _builtins.int
    MAX_STREAM_RECEIVE_WINDOW_FIELD_NUMBER: _builtins.int
    INIT_CONN_RECEIVE_WINDOW_FIELD_NUMBER: _builtins.int
    MAX_CONN_RECEIVE_WINDOW_FIELD_NUMBER: _builtins.int
    MAX_IDLE_TIMEOUT_FIELD_NUMBER: _builtins.int
    KEEP_ALIVE_PERIOD_FIELD_NUMBER: _builtins.int
    DISABLE_PATH_MTU_DISCOVERY_FIELD_NUMBER: _builtins.int
    MAX_INCOMING_STREAMS_FIELD_NUMBER: _builtins.int
    congestion: _builtins.str
    brutal_up: _builtins.int
    brutal_down: _builtins.int
    init_stream_receive_window: _builtins.int
    max_stream_receive_window: _builtins.int
    init_conn_receive_window: _builtins.int
    max_conn_receive_window: _builtins.int
    max_idle_timeout: _builtins.int
    keep_alive_period: _builtins.int
    disable_path_mtu_discovery: _builtins.bool
    max_incoming_streams: _builtins.int
    @_builtins.property
    def udp_hop(self) -> Global___UdpHop: ...
    def __init__(
        self,
        *,
        congestion: _builtins.str = ...,
        brutal_up: _builtins.int = ...,
        brutal_down: _builtins.int = ...,
        udp_hop: Global___UdpHop | None = ...,
        init_stream_receive_window: _builtins.int = ...,
        max_stream_receive_window: _builtins.int = ...,
        init_conn_receive_window: _builtins.int = ...,
        max_conn_receive_window: _builtins.int = ...,
        max_idle_timeout: _builtins.int = ...,
        keep_alive_period: _builtins.int = ...,
        disable_path_mtu_discovery: _builtins.bool = ...,
        max_incoming_streams: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["udp_hop", b"udp_hop"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["brutal_down", b"brutal_down", "brutal_up", b"brutal_up", "congestion", b"congestion", "disable_path_mtu_discovery", b"disable_path_mtu_discovery", "init_conn_receive_window", b"init_conn_receive_window", "init_stream_receive_window", b"init_stream_receive_window", "keep_alive_period", b"keep_alive_period", "max_conn_receive_window", b"max_conn_receive_window", "max_idle_timeout", b"max_idle_timeout", "max_incoming_streams", b"max_incoming_streams", "max_stream_receive_window", b"max_stream_receive_window", "udp_hop", b"udp_hop"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___QuicParams: _TypeAlias = QuicParams  # noqa: Y015

@_typing.final
class ProxyConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    TRANSPORTLAYERPROXY_FIELD_NUMBER: _builtins.int
    tag: _builtins.str
    transportLayerProxy: _builtins.bool
    def __init__(
        self,
        *,
        tag: _builtins.str = ...,
        transportLayerProxy: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tag", b"tag", "transportLayerProxy", b"transportLayerProxy"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProxyConfig: _TypeAlias = ProxyConfig  # noqa: Y015

@_typing.final
class CustomSockopt(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SYSTEM_FIELD_NUMBER: _builtins.int
    NETWORK_FIELD_NUMBER: _builtins.int
    LEVEL_FIELD_NUMBER: _builtins.int
    OPT_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    system: _builtins.str
    network: _builtins.str
    level: _builtins.str
    opt: _builtins.str
    value: _builtins.str
    type: _builtins.str
    def __init__(
        self,
        *,
        system: _builtins.str = ...,
        network: _builtins.str = ...,
        level: _builtins.str = ...,
        opt: _builtins.str = ...,
        value: _builtins.str = ...,
        type: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["level", b"level", "network", b"network", "opt", b"opt", "system", b"system", "type", b"type", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CustomSockopt: _TypeAlias = CustomSockopt  # noqa: Y015

@_typing.final
class SocketConfig(_message.Message):
    """SocketConfig is options to be applied on network sockets."""

    DESCRIPTOR: _descriptor.Descriptor

    class _TProxyMode:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TProxyModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SocketConfig._TProxyMode.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        Off: SocketConfig._TProxyMode.ValueType  # 0
        """TProxy is off."""
        TProxy: SocketConfig._TProxyMode.ValueType  # 1
        """TProxy mode."""
        Redirect: SocketConfig._TProxyMode.ValueType  # 2
        """Redirect mode."""

    class TProxyMode(_TProxyMode, metaclass=_TProxyModeEnumTypeWrapper): ...
    Off: SocketConfig.TProxyMode.ValueType  # 0
    """TProxy is off."""
    TProxy: SocketConfig.TProxyMode.ValueType  # 1
    """TProxy mode."""
    Redirect: SocketConfig.TProxyMode.ValueType  # 2
    """Redirect mode."""

    MARK_FIELD_NUMBER: _builtins.int
    TFO_FIELD_NUMBER: _builtins.int
    TPROXY_FIELD_NUMBER: _builtins.int
    RECEIVE_ORIGINAL_DEST_ADDRESS_FIELD_NUMBER: _builtins.int
    BIND_ADDRESS_FIELD_NUMBER: _builtins.int
    BIND_PORT_FIELD_NUMBER: _builtins.int
    ACCEPT_PROXY_PROTOCOL_FIELD_NUMBER: _builtins.int
    DOMAIN_STRATEGY_FIELD_NUMBER: _builtins.int
    DIALER_PROXY_FIELD_NUMBER: _builtins.int
    TCP_KEEP_ALIVE_INTERVAL_FIELD_NUMBER: _builtins.int
    TCP_KEEP_ALIVE_IDLE_FIELD_NUMBER: _builtins.int
    TCP_CONGESTION_FIELD_NUMBER: _builtins.int
    INTERFACE_FIELD_NUMBER: _builtins.int
    V6ONLY_FIELD_NUMBER: _builtins.int
    TCP_WINDOW_CLAMP_FIELD_NUMBER: _builtins.int
    TCP_USER_TIMEOUT_FIELD_NUMBER: _builtins.int
    TCP_MAX_SEG_FIELD_NUMBER: _builtins.int
    PENETRATE_FIELD_NUMBER: _builtins.int
    TCP_MPTCP_FIELD_NUMBER: _builtins.int
    CUSTOMSOCKOPT_FIELD_NUMBER: _builtins.int
    ADDRESS_PORT_STRATEGY_FIELD_NUMBER: _builtins.int
    HAPPY_EYEBALLS_FIELD_NUMBER: _builtins.int
    TRUSTED_X_FORWARDED_FOR_FIELD_NUMBER: _builtins.int
    mark: _builtins.int
    """Mark of the connection. If non-zero, the value will be set to SO_MARK."""
    tfo: _builtins.int
    """TFO is the state of TFO settings."""
    tproxy: Global___SocketConfig.TProxyMode.ValueType
    """TProxy is for enabling TProxy socket option."""
    receive_original_dest_address: _builtins.bool
    """ReceiveOriginalDestAddress is for enabling IP_RECVORIGDSTADDR socket
    option. This option is for UDP only.
    """
    bind_address: _builtins.bytes
    bind_port: _builtins.int
    accept_proxy_protocol: _builtins.bool
    domain_strategy: Global___DomainStrategy.ValueType
    dialer_proxy: _builtins.str
    tcp_keep_alive_interval: _builtins.int
    tcp_keep_alive_idle: _builtins.int
    tcp_congestion: _builtins.str
    interface: _builtins.str
    v6only: _builtins.bool
    tcp_window_clamp: _builtins.int
    tcp_user_timeout: _builtins.int
    tcp_max_seg: _builtins.int
    penetrate: _builtins.bool
    tcp_mptcp: _builtins.bool
    address_port_strategy: Global___AddressPortStrategy.ValueType
    @_builtins.property
    def customSockopt(self) -> _containers.RepeatedCompositeFieldContainer[Global___CustomSockopt]: ...
    @_builtins.property
    def happy_eyeballs(self) -> Global___HappyEyeballsConfig: ...
    @_builtins.property
    def trusted_x_forwarded_for(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        mark: _builtins.int = ...,
        tfo: _builtins.int = ...,
        tproxy: Global___SocketConfig.TProxyMode.ValueType = ...,
        receive_original_dest_address: _builtins.bool = ...,
        bind_address: _builtins.bytes = ...,
        bind_port: _builtins.int = ...,
        accept_proxy_protocol: _builtins.bool = ...,
        domain_strategy: Global___DomainStrategy.ValueType = ...,
        dialer_proxy: _builtins.str = ...,
        tcp_keep_alive_interval: _builtins.int = ...,
        tcp_keep_alive_idle: _builtins.int = ...,
        tcp_congestion: _builtins.str = ...,
        interface: _builtins.str = ...,
        v6only: _builtins.bool = ...,
        tcp_window_clamp: _builtins.int = ...,
        tcp_user_timeout: _builtins.int = ...,
        tcp_max_seg: _builtins.int = ...,
        penetrate: _builtins.bool = ...,
        tcp_mptcp: _builtins.bool = ...,
        customSockopt: _abc.Iterable[Global___CustomSockopt] | None = ...,
        address_port_strategy: Global___AddressPortStrategy.ValueType = ...,
        happy_eyeballs: Global___HappyEyeballsConfig | None = ...,
        trusted_x_forwarded_for: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["happy_eyeballs", b"happy_eyeballs"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accept_proxy_protocol", b"accept_proxy_protocol", "address_port_strategy", b"address_port_strategy", "bind_address", b"bind_address", "bind_port", b"bind_port", "customSockopt", b"customSockopt", "dialer_proxy", b"dialer_proxy", "domain_strategy", b"domain_strategy", "happy_eyeballs", b"happy_eyeballs", "interface", b"interface", "mark", b"mark", "penetrate", b"penetrate", "receive_original_dest_address", b"receive_original_dest_address", "tcp_congestion", b"tcp_congestion", "tcp_keep_alive_idle", b"tcp_keep_alive_idle", "tcp_keep_alive_interval", b"tcp_keep_alive_interval", "tcp_max_seg", b"tcp_max_seg", "tcp_mptcp", b"tcp_mptcp", "tcp_user_timeout", b"tcp_user_timeout", "tcp_window_clamp", b"tcp_window_clamp", "tfo", b"tfo", "tproxy", b"tproxy", "trusted_x_forwarded_for", b"trusted_x_forwarded_for", "v6only", b"v6only"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SocketConfig: _TypeAlias = SocketConfig  # noqa: Y015

@_typing.final
class HappyEyeballsConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PRIORITIZE_IPV6_FIELD_NUMBER: _builtins.int
    INTERLEAVE_FIELD_NUMBER: _builtins.int
    TRY_DELAYMS_FIELD_NUMBER: _builtins.int
    MAX_CONCURRENT_TRY_FIELD_NUMBER: _builtins.int
    prioritize_ipv6: _builtins.bool
    interleave: _builtins.int
    try_delayMs: _builtins.int
    max_concurrent_try: _builtins.int
    def __init__(
        self,
        *,
        prioritize_ipv6: _builtins.bool = ...,
        interleave: _builtins.int = ...,
        try_delayMs: _builtins.int = ...,
        max_concurrent_try: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["interleave", b"interleave", "max_concurrent_try", b"max_concurrent_try", "prioritize_ipv6", b"prioritize_ipv6", "try_delayMs", b"try_delayMs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HappyEyeballsConfig: _TypeAlias = HappyEyeballsConfig  # noqa: Y015
