"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from common.log import log_pb2 as _log_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _LogType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _LogTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_LogType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    Console: _LogType.ValueType  # 1
    File: _LogType.ValueType  # 2
    Event: _LogType.ValueType  # 3

class LogType(_LogType, metaclass=_LogTypeEnumTypeWrapper): ...

Console: LogType.ValueType  # 1
File: LogType.ValueType  # 2
Event: LogType.ValueType  # 3
Global___LogType: _TypeAlias = LogType  # noqa: Y015

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_LOG_TYPE_FIELD_NUMBER: _builtins.int
    ERROR_LOG_LEVEL_FIELD_NUMBER: _builtins.int
    ERROR_LOG_PATH_FIELD_NUMBER: _builtins.int
    ACCESS_LOG_TYPE_FIELD_NUMBER: _builtins.int
    ACCESS_LOG_PATH_FIELD_NUMBER: _builtins.int
    ENABLE_DNS_LOG_FIELD_NUMBER: _builtins.int
    MASK_ADDRESS_FIELD_NUMBER: _builtins.int
    error_log_type: Global___LogType.ValueType
    error_log_level: _log_pb2.Severity.ValueType
    error_log_path: _builtins.str
    access_log_type: Global___LogType.ValueType
    access_log_path: _builtins.str
    enable_dns_log: _builtins.bool
    mask_address: _builtins.str
    def __init__(
        self,
        *,
        error_log_type: Global___LogType.ValueType = ...,
        error_log_level: _log_pb2.Severity.ValueType = ...,
        error_log_path: _builtins.str = ...,
        access_log_type: Global___LogType.ValueType = ...,
        access_log_path: _builtins.str = ...,
        enable_dns_log: _builtins.bool = ...,
        mask_address: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["access_log_path", b"access_log_path", "access_log_type", b"access_log_type", "enable_dns_log", b"enable_dns_log", "error_log_level", b"error_log_level", "error_log_path", b"error_log_path", "error_log_type", b"error_log_type", "mask_address", b"mask_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
