"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from transport.internet import config_pb2 as _config_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Certificate(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Usage:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _UsageEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Certificate._Usage.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        ENCIPHERMENT: Certificate._Usage.ValueType  # 0
        AUTHORITY_VERIFY: Certificate._Usage.ValueType  # 1
        AUTHORITY_ISSUE: Certificate._Usage.ValueType  # 2

    class Usage(_Usage, metaclass=_UsageEnumTypeWrapper): ...
    ENCIPHERMENT: Certificate.Usage.ValueType  # 0
    AUTHORITY_VERIFY: Certificate.Usage.ValueType  # 1
    AUTHORITY_ISSUE: Certificate.Usage.ValueType  # 2

    CERTIFICATE_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    USAGE_FIELD_NUMBER: _builtins.int
    OCSP_STAPLING_FIELD_NUMBER: _builtins.int
    CERTIFICATE_PATH_FIELD_NUMBER: _builtins.int
    KEY_PATH_FIELD_NUMBER: _builtins.int
    ONE_TIME_LOADING_FIELD_NUMBER: _builtins.int
    BUILD_CHAIN_FIELD_NUMBER: _builtins.int
    certificate: _builtins.bytes
    """TLS certificate in x509 format."""
    key: _builtins.bytes
    """TLS key in x509 format."""
    usage: Global___Certificate.Usage.ValueType
    ocsp_stapling: _builtins.int
    certificate_path: _builtins.str
    """TLS certificate path"""
    key_path: _builtins.str
    """TLS Key path"""
    One_time_loading: _builtins.bool
    """If true, one-Time Loading"""
    build_chain: _builtins.bool
    def __init__(
        self,
        *,
        certificate: _builtins.bytes = ...,
        key: _builtins.bytes = ...,
        usage: Global___Certificate.Usage.ValueType = ...,
        ocsp_stapling: _builtins.int = ...,
        certificate_path: _builtins.str = ...,
        key_path: _builtins.str = ...,
        One_time_loading: _builtins.bool = ...,
        build_chain: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["One_time_loading", b"One_time_loading", "build_chain", b"build_chain", "certificate", b"certificate", "certificate_path", b"certificate_path", "key", b"key", "key_path", b"key_path", "ocsp_stapling", b"ocsp_stapling", "usage", b"usage"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Certificate: _TypeAlias = Certificate  # noqa: Y015

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ALLOW_INSECURE_FIELD_NUMBER: _builtins.int
    CERTIFICATE_FIELD_NUMBER: _builtins.int
    SERVER_NAME_FIELD_NUMBER: _builtins.int
    NEXT_PROTOCOL_FIELD_NUMBER: _builtins.int
    ENABLE_SESSION_RESUMPTION_FIELD_NUMBER: _builtins.int
    DISABLE_SYSTEM_ROOT_FIELD_NUMBER: _builtins.int
    MIN_VERSION_FIELD_NUMBER: _builtins.int
    MAX_VERSION_FIELD_NUMBER: _builtins.int
    CIPHER_SUITES_FIELD_NUMBER: _builtins.int
    FINGERPRINT_FIELD_NUMBER: _builtins.int
    REJECT_UNKNOWN_SNI_FIELD_NUMBER: _builtins.int
    MASTER_KEY_LOG_FIELD_NUMBER: _builtins.int
    CURVE_PREFERENCES_FIELD_NUMBER: _builtins.int
    VERIFY_PEER_CERT_BY_NAME_FIELD_NUMBER: _builtins.int
    ECH_SERVER_KEYS_FIELD_NUMBER: _builtins.int
    ECH_CONFIG_LIST_FIELD_NUMBER: _builtins.int
    ECH_FORCE_QUERY_FIELD_NUMBER: _builtins.int
    ECH_SOCKET_SETTINGS_FIELD_NUMBER: _builtins.int
    PINNED_PEER_CERT_SHA256_FIELD_NUMBER: _builtins.int
    allow_insecure: _builtins.bool
    server_name: _builtins.str
    """Override server name."""
    enable_session_resumption: _builtins.bool
    """Whether or not to enable session (ticket) resumption."""
    disable_system_root: _builtins.bool
    """If true, root certificates on the system will not be loaded for
    verification.
    """
    min_version: _builtins.str
    """The minimum TLS version."""
    max_version: _builtins.str
    """The maximum TLS version."""
    cipher_suites: _builtins.str
    """Specify cipher suites, except for TLS 1.3."""
    fingerprint: _builtins.str
    """TLS Client Hello fingerprint (uTLS)."""
    reject_unknown_sni: _builtins.bool
    master_key_log: _builtins.str
    ech_server_keys: _builtins.bytes
    ech_config_list: _builtins.str
    ech_force_query: _builtins.str
    @_builtins.property
    def certificate(self) -> _containers.RepeatedCompositeFieldContainer[Global___Certificate]:
        """List of certificates to be served on server."""

    @_builtins.property
    def next_protocol(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Lists of string as ALPN values."""

    @_builtins.property
    def curve_preferences(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Lists of string as CurvePreferences values."""

    @_builtins.property
    def verify_peer_cert_by_name(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def ech_socket_settings(self) -> _config_pb2.SocketConfig: ...
    @_builtins.property
    def pinned_peer_cert_sha256(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
    def __init__(
        self,
        *,
        allow_insecure: _builtins.bool = ...,
        certificate: _abc.Iterable[Global___Certificate] | None = ...,
        server_name: _builtins.str = ...,
        next_protocol: _abc.Iterable[_builtins.str] | None = ...,
        enable_session_resumption: _builtins.bool = ...,
        disable_system_root: _builtins.bool = ...,
        min_version: _builtins.str = ...,
        max_version: _builtins.str = ...,
        cipher_suites: _builtins.str = ...,
        fingerprint: _builtins.str = ...,
        reject_unknown_sni: _builtins.bool = ...,
        master_key_log: _builtins.str = ...,
        curve_preferences: _abc.Iterable[_builtins.str] | None = ...,
        verify_peer_cert_by_name: _abc.Iterable[_builtins.str] | None = ...,
        ech_server_keys: _builtins.bytes = ...,
        ech_config_list: _builtins.str = ...,
        ech_force_query: _builtins.str = ...,
        ech_socket_settings: _config_pb2.SocketConfig | None = ...,
        pinned_peer_cert_sha256: _abc.Iterable[_builtins.bytes] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ech_socket_settings", b"ech_socket_settings"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_insecure", b"allow_insecure", "certificate", b"certificate", "cipher_suites", b"cipher_suites", "curve_preferences", b"curve_preferences", "disable_system_root", b"disable_system_root", "ech_config_list", b"ech_config_list", "ech_force_query", b"ech_force_query", "ech_server_keys", b"ech_server_keys", "ech_socket_settings", b"ech_socket_settings", "enable_session_resumption", b"enable_session_resumption", "fingerprint", b"fingerprint", "master_key_log", b"master_key_log", "max_version", b"max_version", "min_version", b"min_version", "next_protocol", b"next_protocol", "pinned_peer_cert_sha256", b"pinned_peer_cert_sha256", "reject_unknown_sni", b"reject_unknown_sni", "server_name", b"server_name", "verify_peer_cert_by_name", b"verify_peer_cert_by_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
