"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from common.protocol import headers_pb2 as _headers_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Account(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    SECURITY_SETTINGS_FIELD_NUMBER: _builtins.int
    TESTS_ENABLED_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """ID of the account, in the form of a UUID, e.g.,
    "66ad4540-b58c-4ad2-9926-ea63445a9b57".
    """
    tests_enabled: _builtins.str
    """Define tests enabled for this account"""
    @_builtins.property
    def security_settings(self) -> _headers_pb2.SecurityConfig:
        """Security settings. Only applies to client side."""

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        security_settings: _headers_pb2.SecurityConfig | None = ...,
        tests_enabled: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["security_settings", b"security_settings"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "security_settings", b"security_settings", "tests_enabled", b"tests_enabled"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Account: _TypeAlias = Account  # noqa: Y015
