"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from common.serial import typed_message_pb2 as _typed_message_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HEADER_SETTINGS_FIELD_NUMBER: _builtins.int
    ACCEPT_PROXY_PROTOCOL_FIELD_NUMBER: _builtins.int
    accept_proxy_protocol: _builtins.bool
    @_builtins.property
    def header_settings(self) -> _typed_message_pb2.TypedMessage: ...
    def __init__(
        self,
        *,
        header_settings: _typed_message_pb2.TypedMessage | None = ...,
        accept_proxy_protocol: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header_settings", b"header_settings"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accept_proxy_protocol", b"accept_proxy_protocol", "header_settings", b"header_settings"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
