# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/finalmask/mkcp/aes128gcm/config.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'transport/internet/finalmask/mkcp/aes128gcm/config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8transport/internet/finalmask/mkcp/aes128gcm/config.proto\x12\x30xray.transport.internet.finalmask.mkcp.aes128gcm\"\x1a\n\x06\x43onfig\x12\x10\n\x08password\x18\x01 \x01(\tB\xb2\x01\n4com.xray.transport.internet.finalmask.mkcp.aes128gcmP\x01ZEgithub.com/xtls/xray-core/transport/internet/finalmask/mkcp/aes128gcm\xaa\x02\x30Xray.Transport.Internet.Finalmask.Mkcp.Aes128Gcmb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.finalmask.mkcp.aes128gcm.config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n4com.xray.transport.internet.finalmask.mkcp.aes128gcmP\001ZEgithub.com/xtls/xray-core/transport/internet/finalmask/mkcp/aes128gcm\252\0020Xray.Transport.Internet.Finalmask.Mkcp.Aes128Gcm'
  _globals['_CONFIG']._serialized_start=110
  _globals['_CONFIG']._serialized_end=136
# @@protoc_insertion_point(module_scope)
