"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from common.serial import typed_message_pb2 as _typed_message_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class MTU(_message.Message):
    """Maximum Transmission Unit, in bytes."""

    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.int
    def __init__(
        self,
        *,
        value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MTU: _TypeAlias = MTU  # noqa: Y015

@_typing.final
class TTI(_message.Message):
    """Transmission Time Interview, in milli-sec."""

    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.int
    def __init__(
        self,
        *,
        value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TTI: _TypeAlias = TTI  # noqa: Y015

@_typing.final
class UplinkCapacity(_message.Message):
    """Uplink capacity, in MB."""

    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.int
    def __init__(
        self,
        *,
        value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UplinkCapacity: _TypeAlias = UplinkCapacity  # noqa: Y015

@_typing.final
class DownlinkCapacity(_message.Message):
    """Downlink capacity, in MB."""

    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.int
    def __init__(
        self,
        *,
        value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DownlinkCapacity: _TypeAlias = DownlinkCapacity  # noqa: Y015

@_typing.final
class WriteBuffer(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SIZE_FIELD_NUMBER: _builtins.int
    size: _builtins.int
    """Buffer size in bytes."""
    def __init__(
        self,
        *,
        size: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["size", b"size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WriteBuffer: _TypeAlias = WriteBuffer  # noqa: Y015

@_typing.final
class ReadBuffer(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SIZE_FIELD_NUMBER: _builtins.int
    size: _builtins.int
    """Buffer size in bytes."""
    def __init__(
        self,
        *,
        size: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["size", b"size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReadBuffer: _TypeAlias = ReadBuffer  # noqa: Y015

@_typing.final
class ConnectionReuse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENABLE_FIELD_NUMBER: _builtins.int
    enable: _builtins.bool
    def __init__(
        self,
        *,
        enable: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enable", b"enable"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ConnectionReuse: _TypeAlias = ConnectionReuse  # noqa: Y015

@_typing.final
class EncryptionSeed(_message.Message):
    """Pre-shared secret between client and server. It is used for traffic obfuscation.
    Note that if seed is absent in the config, the traffic will still be obfuscated,
    but by a predefined algorithm.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SEED_FIELD_NUMBER: _builtins.int
    seed: _builtins.str
    def __init__(
        self,
        *,
        seed: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["seed", b"seed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EncryptionSeed: _TypeAlias = EncryptionSeed  # noqa: Y015

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MTU_FIELD_NUMBER: _builtins.int
    TTI_FIELD_NUMBER: _builtins.int
    UPLINK_CAPACITY_FIELD_NUMBER: _builtins.int
    DOWNLINK_CAPACITY_FIELD_NUMBER: _builtins.int
    CONGESTION_FIELD_NUMBER: _builtins.int
    WRITE_BUFFER_FIELD_NUMBER: _builtins.int
    READ_BUFFER_FIELD_NUMBER: _builtins.int
    HEADER_CONFIG_FIELD_NUMBER: _builtins.int
    SEED_FIELD_NUMBER: _builtins.int
    congestion: _builtins.bool
    @_builtins.property
    def mtu(self) -> Global___MTU: ...
    @_builtins.property
    def tti(self) -> Global___TTI: ...
    @_builtins.property
    def uplink_capacity(self) -> Global___UplinkCapacity: ...
    @_builtins.property
    def downlink_capacity(self) -> Global___DownlinkCapacity: ...
    @_builtins.property
    def write_buffer(self) -> Global___WriteBuffer: ...
    @_builtins.property
    def read_buffer(self) -> Global___ReadBuffer: ...
    @_builtins.property
    def header_config(self) -> _typed_message_pb2.TypedMessage: ...
    @_builtins.property
    def seed(self) -> Global___EncryptionSeed: ...
    def __init__(
        self,
        *,
        mtu: Global___MTU | None = ...,
        tti: Global___TTI | None = ...,
        uplink_capacity: Global___UplinkCapacity | None = ...,
        downlink_capacity: Global___DownlinkCapacity | None = ...,
        congestion: _builtins.bool = ...,
        write_buffer: Global___WriteBuffer | None = ...,
        read_buffer: Global___ReadBuffer | None = ...,
        header_config: _typed_message_pb2.TypedMessage | None = ...,
        seed: Global___EncryptionSeed | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["downlink_capacity", b"downlink_capacity", "header_config", b"header_config", "mtu", b"mtu", "read_buffer", b"read_buffer", "seed", b"seed", "tti", b"tti", "uplink_capacity", b"uplink_capacity", "write_buffer", b"write_buffer"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["congestion", b"congestion", "downlink_capacity", b"downlink_capacity", "header_config", b"header_config", "mtu", b"mtu", "read_buffer", b"read_buffer", "seed", b"seed", "tti", b"tti", "uplink_capacity", b"uplink_capacity", "write_buffer", b"write_buffer"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
