"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from common.protocol import server_spec_pb2 as _server_spec_pb2
from common.protocol import user_pb2 as _user_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Account(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PASSWORD_FIELD_NUMBER: _builtins.int
    password: _builtins.str
    def __init__(
        self,
        *,
        password: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["password", b"password"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Account: _TypeAlias = Account  # noqa: Y015

@_typing.final
class Fallback(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    ALPN_FIELD_NUMBER: _builtins.int
    PATH_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    DEST_FIELD_NUMBER: _builtins.int
    XVER_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    alpn: _builtins.str
    path: _builtins.str
    type: _builtins.str
    dest: _builtins.str
    xver: _builtins.int
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        alpn: _builtins.str = ...,
        path: _builtins.str = ...,
        type: _builtins.str = ...,
        dest: _builtins.str = ...,
        xver: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["alpn", b"alpn", "dest", b"dest", "name", b"name", "path", b"path", "type", b"type", "xver", b"xver"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Fallback: _TypeAlias = Fallback  # noqa: Y015

@_typing.final
class ClientConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SERVER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def server(self) -> _server_spec_pb2.ServerEndpoint: ...
    def __init__(
        self,
        *,
        server: _server_spec_pb2.ServerEndpoint | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["server", b"server"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["server", b"server"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ClientConfig: _TypeAlias = ClientConfig  # noqa: Y015

@_typing.final
class ServerConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERS_FIELD_NUMBER: _builtins.int
    FALLBACKS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def users(self) -> _containers.RepeatedCompositeFieldContainer[_user_pb2.User]: ...
    @_builtins.property
    def fallbacks(self) -> _containers.RepeatedCompositeFieldContainer[Global___Fallback]: ...
    def __init__(
        self,
        *,
        users: _abc.Iterable[_user_pb2.User] | None = ...,
        fallbacks: _abc.Iterable[Global___Fallback] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fallbacks", b"fallbacks", "users", b"users"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ServerConfig: _TypeAlias = ServerConfig  # noqa: Y015
