"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Addons(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FLOW_FIELD_NUMBER: _builtins.int
    SEED_FIELD_NUMBER: _builtins.int
    Flow: _builtins.str
    Seed: _builtins.bytes
    def __init__(
        self,
        *,
        Flow: _builtins.str = ...,
        Seed: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["Flow", b"Flow", "Seed", b"Seed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Addons: _TypeAlias = Addons  # noqa: Y015
