"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Item(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RAND_MIN_FIELD_NUMBER: _builtins.int
    RAND_MAX_FIELD_NUMBER: _builtins.int
    RAND_RANGE_MIN_FIELD_NUMBER: _builtins.int
    RAND_RANGE_MAX_FIELD_NUMBER: _builtins.int
    PACKET_FIELD_NUMBER: _builtins.int
    DELAY_MIN_FIELD_NUMBER: _builtins.int
    DELAY_MAX_FIELD_NUMBER: _builtins.int
    rand_min: _builtins.int
    rand_max: _builtins.int
    rand_range_min: _builtins.int
    rand_range_max: _builtins.int
    packet: _builtins.bytes
    delay_min: _builtins.int
    delay_max: _builtins.int
    def __init__(
        self,
        *,
        rand_min: _builtins.int = ...,
        rand_max: _builtins.int = ...,
        rand_range_min: _builtins.int = ...,
        rand_range_max: _builtins.int = ...,
        packet: _builtins.bytes = ...,
        delay_min: _builtins.int = ...,
        delay_max: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["delay_max", b"delay_max", "delay_min", b"delay_min", "packet", b"packet", "rand_max", b"rand_max", "rand_min", b"rand_min", "rand_range_max", b"rand_range_max", "rand_range_min", b"rand_range_min"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Item: _TypeAlias = Item  # noqa: Y015

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESET_MIN_FIELD_NUMBER: _builtins.int
    RESET_MAX_FIELD_NUMBER: _builtins.int
    ITEMS_FIELD_NUMBER: _builtins.int
    reset_min: _builtins.int
    reset_max: _builtins.int
    @_builtins.property
    def items(self) -> _containers.RepeatedCompositeFieldContainer[Global___Item]: ...
    def __init__(
        self,
        *,
        reset_min: _builtins.int = ...,
        reset_max: _builtins.int = ...,
        items: _abc.Iterable[Global___Item] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["items", b"items", "reset_max", b"reset_max", "reset_min", b"reset_min"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
