"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from common.net import address_pb2 as _address_pb2
from common.protocol import server_spec_pb2 as _server_spec_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _AuthType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _AuthTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_AuthType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    NO_AUTH: _AuthType.ValueType  # 0
    """NO_AUTH is for anonymous authentication."""
    PASSWORD: _AuthType.ValueType  # 1
    """PASSWORD is for username/password authentication."""

class AuthType(_AuthType, metaclass=_AuthTypeEnumTypeWrapper):
    """AuthType is the authentication type of Socks proxy."""

NO_AUTH: AuthType.ValueType  # 0
"""NO_AUTH is for anonymous authentication."""
PASSWORD: AuthType.ValueType  # 1
"""PASSWORD is for username/password authentication."""
Global___AuthType: _TypeAlias = AuthType  # noqa: Y015

@_typing.final
class Account(_message.Message):
    """Account represents a Socks account."""

    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_FIELD_NUMBER: _builtins.int
    PASSWORD_FIELD_NUMBER: _builtins.int
    username: _builtins.str
    password: _builtins.str
    def __init__(
        self,
        *,
        username: _builtins.str = ...,
        password: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["password", b"password", "username", b"username"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Account: _TypeAlias = Account  # noqa: Y015

@_typing.final
class ServerConfig(_message.Message):
    """ServerConfig is the protobuf config for Socks server."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class AccountsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    AUTH_TYPE_FIELD_NUMBER: _builtins.int
    ACCOUNTS_FIELD_NUMBER: _builtins.int
    ADDRESS_FIELD_NUMBER: _builtins.int
    UDP_ENABLED_FIELD_NUMBER: _builtins.int
    USER_LEVEL_FIELD_NUMBER: _builtins.int
    auth_type: Global___AuthType.ValueType
    udp_enabled: _builtins.bool
    user_level: _builtins.int
    @_builtins.property
    def accounts(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def address(self) -> _address_pb2.IPOrDomain: ...
    def __init__(
        self,
        *,
        auth_type: Global___AuthType.ValueType = ...,
        accounts: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        address: _address_pb2.IPOrDomain | None = ...,
        udp_enabled: _builtins.bool = ...,
        user_level: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["address", b"address"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accounts", b"accounts", "address", b"address", "auth_type", b"auth_type", "udp_enabled", b"udp_enabled", "user_level", b"user_level"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ServerConfig: _TypeAlias = ServerConfig  # noqa: Y015

@_typing.final
class ClientConfig(_message.Message):
    """ClientConfig is the protobuf config for Socks client."""

    DESCRIPTOR: _descriptor.Descriptor

    SERVER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def server(self) -> _server_spec_pb2.ServerEndpoint:
        """Sever is a list of Socks server addresses."""

    def __init__(
        self,
        *,
        server: _server_spec_pb2.ServerEndpoint | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["server", b"server"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["server", b"server"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ClientConfig: _TypeAlias = ClientConfig  # noqa: Y015
