"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _Severity:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SeverityEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Severity.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    Unknown: _Severity.ValueType  # 0
    Error: _Severity.ValueType  # 1
    Warning: _Severity.ValueType  # 2
    Info: _Severity.ValueType  # 3
    Debug: _Severity.ValueType  # 4

class Severity(_Severity, metaclass=_SeverityEnumTypeWrapper): ...

Unknown: Severity.ValueType  # 0
Error: Severity.ValueType  # 1
Warning: Severity.ValueType  # 2
Info: Severity.ValueType  # 3
Debug: Severity.ValueType  # 4
Global___Severity: _TypeAlias = Severity  # noqa: Y015
