"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from common.protocol import server_spec_pb2 as _server_spec_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Account(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_FIELD_NUMBER: _builtins.int
    PASSWORD_FIELD_NUMBER: _builtins.int
    username: _builtins.str
    password: _builtins.str
    def __init__(
        self,
        *,
        username: _builtins.str = ...,
        password: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["password", b"password", "username", b"username"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Account: _TypeAlias = Account  # noqa: Y015

@_typing.final
class ServerConfig(_message.Message):
    """Config for HTTP proxy server."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class AccountsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    ACCOUNTS_FIELD_NUMBER: _builtins.int
    ALLOW_TRANSPARENT_FIELD_NUMBER: _builtins.int
    USER_LEVEL_FIELD_NUMBER: _builtins.int
    allow_transparent: _builtins.bool
    user_level: _builtins.int
    @_builtins.property
    def accounts(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        accounts: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        allow_transparent: _builtins.bool = ...,
        user_level: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accounts", b"accounts", "allow_transparent", b"allow_transparent", "user_level", b"user_level"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ServerConfig: _TypeAlias = ServerConfig  # noqa: Y015

@_typing.final
class Header(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.str
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        value: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Header: _TypeAlias = Header  # noqa: Y015

@_typing.final
class ClientConfig(_message.Message):
    """ClientConfig is the protobuf config for HTTP proxy client."""

    DESCRIPTOR: _descriptor.Descriptor

    SERVER_FIELD_NUMBER: _builtins.int
    HEADER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def server(self) -> _server_spec_pb2.ServerEndpoint:
        """Sever is a list of HTTP server addresses."""

    @_builtins.property
    def header(self) -> _containers.RepeatedCompositeFieldContainer[Global___Header]: ...
    def __init__(
        self,
        *,
        server: _server_spec_pb2.ServerEndpoint | None = ...,
        header: _abc.Iterable[Global___Header] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["server", b"server"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["header", b"header", "server", b"server"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ClientConfig: _TypeAlias = ClientConfig  # noqa: Y015
