"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from common.net import address_pb2 as _address_pb2
from common.net import network_pb2 as _network_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class PortMapEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    ADDRESS_FIELD_NUMBER: _builtins.int
    PORT_FIELD_NUMBER: _builtins.int
    PORT_MAP_FIELD_NUMBER: _builtins.int
    NETWORKS_FIELD_NUMBER: _builtins.int
    FOLLOW_REDIRECT_FIELD_NUMBER: _builtins.int
    USER_LEVEL_FIELD_NUMBER: _builtins.int
    port: _builtins.int
    follow_redirect: _builtins.bool
    user_level: _builtins.int
    @_builtins.property
    def address(self) -> _address_pb2.IPOrDomain: ...
    @_builtins.property
    def port_map(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def networks(self) -> _containers.RepeatedScalarFieldContainer[_network_pb2.Network.ValueType]:
        """List of networks that the Dokodemo accepts."""

    def __init__(
        self,
        *,
        address: _address_pb2.IPOrDomain | None = ...,
        port: _builtins.int = ...,
        port_map: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        networks: _abc.Iterable[_network_pb2.Network.ValueType] | None = ...,
        follow_redirect: _builtins.bool = ...,
        user_level: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["address", b"address"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "follow_redirect", b"follow_redirect", "networks", b"networks", "port", b"port", "port_map", b"port_map", "user_level", b"user_level"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
