"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015

@_typing.final
class ChannelConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BLOCKING_FIELD_NUMBER: _builtins.int
    SUBSCRIBERLIMIT_FIELD_NUMBER: _builtins.int
    BUFFERSIZE_FIELD_NUMBER: _builtins.int
    Blocking: _builtins.bool
    SubscriberLimit: _builtins.int
    BufferSize: _builtins.int
    def __init__(
        self,
        *,
        Blocking: _builtins.bool = ...,
        SubscriberLimit: _builtins.int = ...,
        BufferSize: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["Blocking", b"Blocking", "BufferSize", b"BufferSize", "SubscriberLimit", b"SubscriberLimit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ChannelConfig: _TypeAlias = ChannelConfig  # noqa: Y015
