"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Second(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.int
    def __init__(
        self,
        *,
        value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Second: _TypeAlias = Second  # noqa: Y015

@_typing.final
class Policy(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Timeout(_message.Message):
        """Timeout is a message for timeout settings in various stages, in seconds."""

        DESCRIPTOR: _descriptor.Descriptor

        HANDSHAKE_FIELD_NUMBER: _builtins.int
        CONNECTION_IDLE_FIELD_NUMBER: _builtins.int
        UPLINK_ONLY_FIELD_NUMBER: _builtins.int
        DOWNLINK_ONLY_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def handshake(self) -> Global___Second: ...
        @_builtins.property
        def connection_idle(self) -> Global___Second: ...
        @_builtins.property
        def uplink_only(self) -> Global___Second: ...
        @_builtins.property
        def downlink_only(self) -> Global___Second: ...
        def __init__(
            self,
            *,
            handshake: Global___Second | None = ...,
            connection_idle: Global___Second | None = ...,
            uplink_only: Global___Second | None = ...,
            downlink_only: Global___Second | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["connection_idle", b"connection_idle", "downlink_only", b"downlink_only", "handshake", b"handshake", "uplink_only", b"uplink_only"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["connection_idle", b"connection_idle", "downlink_only", b"downlink_only", "handshake", b"handshake", "uplink_only", b"uplink_only"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class Stats(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        USER_UPLINK_FIELD_NUMBER: _builtins.int
        USER_DOWNLINK_FIELD_NUMBER: _builtins.int
        USER_ONLINE_FIELD_NUMBER: _builtins.int
        user_uplink: _builtins.bool
        user_downlink: _builtins.bool
        user_online: _builtins.bool
        def __init__(
            self,
            *,
            user_uplink: _builtins.bool = ...,
            user_downlink: _builtins.bool = ...,
            user_online: _builtins.bool = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["user_downlink", b"user_downlink", "user_online", b"user_online", "user_uplink", b"user_uplink"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class Buffer(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        CONNECTION_FIELD_NUMBER: _builtins.int
        connection: _builtins.int
        """Buffer size per connection, in bytes. -1 for unlimited buffer."""
        def __init__(
            self,
            *,
            connection: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["connection", b"connection"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    TIMEOUT_FIELD_NUMBER: _builtins.int
    STATS_FIELD_NUMBER: _builtins.int
    BUFFER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def timeout(self) -> Global___Policy.Timeout: ...
    @_builtins.property
    def stats(self) -> Global___Policy.Stats: ...
    @_builtins.property
    def buffer(self) -> Global___Policy.Buffer: ...
    def __init__(
        self,
        *,
        timeout: Global___Policy.Timeout | None = ...,
        stats: Global___Policy.Stats | None = ...,
        buffer: Global___Policy.Buffer | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["buffer", b"buffer", "stats", b"stats", "timeout", b"timeout"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["buffer", b"buffer", "stats", b"stats", "timeout", b"timeout"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Policy: _TypeAlias = Policy  # noqa: Y015

@_typing.final
class SystemPolicy(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Stats(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        INBOUND_UPLINK_FIELD_NUMBER: _builtins.int
        INBOUND_DOWNLINK_FIELD_NUMBER: _builtins.int
        OUTBOUND_UPLINK_FIELD_NUMBER: _builtins.int
        OUTBOUND_DOWNLINK_FIELD_NUMBER: _builtins.int
        inbound_uplink: _builtins.bool
        inbound_downlink: _builtins.bool
        outbound_uplink: _builtins.bool
        outbound_downlink: _builtins.bool
        def __init__(
            self,
            *,
            inbound_uplink: _builtins.bool = ...,
            inbound_downlink: _builtins.bool = ...,
            outbound_uplink: _builtins.bool = ...,
            outbound_downlink: _builtins.bool = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["inbound_downlink", b"inbound_downlink", "inbound_uplink", b"inbound_uplink", "outbound_downlink", b"outbound_downlink", "outbound_uplink", b"outbound_uplink"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    STATS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def stats(self) -> Global___SystemPolicy.Stats: ...
    def __init__(
        self,
        *,
        stats: Global___SystemPolicy.Stats | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stats", b"stats"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stats", b"stats"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SystemPolicy: _TypeAlias = SystemPolicy  # noqa: Y015

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class LevelEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        @_builtins.property
        def value(self) -> Global___Policy: ...
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: Global___Policy | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    LEVEL_FIELD_NUMBER: _builtins.int
    SYSTEM_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def level(self) -> _containers.MessageMap[_builtins.int, Global___Policy]: ...
    @_builtins.property
    def system(self) -> Global___SystemPolicy: ...
    def __init__(
        self,
        *,
        level: _abc.Mapping[_builtins.int, Global___Policy] | None = ...,
        system: Global___SystemPolicy | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["system", b"system"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["level", b"level", "system", b"system"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
