"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PASSWORD_FIELD_NUMBER: _builtins.int
    ASCII_FIELD_NUMBER: _builtins.int
    CUSTOM_TABLE_FIELD_NUMBER: _builtins.int
    PADDING_MIN_FIELD_NUMBER: _builtins.int
    PADDING_MAX_FIELD_NUMBER: _builtins.int
    CUSTOM_TABLES_FIELD_NUMBER: _builtins.int
    password: _builtins.str
    ascii: _builtins.str
    custom_table: _builtins.str
    padding_min: _builtins.int
    padding_max: _builtins.int
    @_builtins.property
    def custom_tables(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        password: _builtins.str = ...,
        ascii: _builtins.str = ...,
        custom_table: _builtins.str = ...,
        padding_min: _builtins.int = ...,
        padding_max: _builtins.int = ...,
        custom_tables: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ascii", b"ascii", "custom_table", b"custom_table", "custom_tables", b"custom_tables", "padding_max", b"padding_max", "padding_min", b"padding_min", "password", b"password"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
