# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/finalmask/sudoku/config.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'transport/internet/finalmask/sudoku/config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0transport/internet/finalmask/sudoku/config.proto\x12(xray.transport.internet.finalmask.sudoku\"\x80\x01\n\x06\x43onfig\x12\x10\n\x08password\x18\x01 \x01(\t\x12\r\n\x05\x61scii\x18\x02 \x01(\t\x12\x14\n\x0c\x63ustom_table\x18\x03 \x01(\t\x12\x13\n\x0bpadding_min\x18\x04 \x01(\r\x12\x13\n\x0bpadding_max\x18\x05 \x01(\r\x12\x15\n\rcustom_tables\x18\x07 \x03(\tB\x9a\x01\n,com.xray.transport.internet.finalmask.sudokuP\x01Z=github.com/xtls/xray-core/transport/internet/finalmask/sudoku\xaa\x02(Xray.Transport.Internet.Finalmask.Sudokub\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.finalmask.sudoku.config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n,com.xray.transport.internet.finalmask.sudokuP\001Z=github.com/xtls/xray-core/transport/internet/finalmask/sudoku\252\002(Xray.Transport.Internet.Finalmask.Sudoku'
  _globals['_CONFIG']._serialized_start=95
  _globals['_CONFIG']._serialized_end=223
# @@protoc_insertion_point(module_scope)
