"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUBJECT_SELECTOR_FIELD_NUMBER: _builtins.int
    PING_CONFIG_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def subject_selector(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """@Document The selectors for outbound under observation"""

    @_builtins.property
    def ping_config(self) -> Global___HealthPingConfig: ...
    def __init__(
        self,
        *,
        subject_selector: _abc.Iterable[_builtins.str] | None = ...,
        ping_config: Global___HealthPingConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ping_config", b"ping_config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ping_config", b"ping_config", "subject_selector", b"subject_selector"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015

@_typing.final
class HealthPingConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DESTINATION_FIELD_NUMBER: _builtins.int
    CONNECTIVITY_FIELD_NUMBER: _builtins.int
    INTERVAL_FIELD_NUMBER: _builtins.int
    SAMPLINGCOUNT_FIELD_NUMBER: _builtins.int
    TIMEOUT_FIELD_NUMBER: _builtins.int
    HTTPMETHOD_FIELD_NUMBER: _builtins.int
    destination: _builtins.str
    """destination url, need 204 for success return
    default https://connectivitycheck.gstatic.com/generate_204
    """
    connectivity: _builtins.str
    """connectivity check url"""
    interval: _builtins.int
    """health check interval, int64 values of time.Duration"""
    samplingCount: _builtins.int
    """sampling count is the amount of recent ping results which are kept for calculation"""
    timeout: _builtins.int
    """ping timeout, int64 values of time.Duration"""
    httpMethod: _builtins.str
    """http method to make request"""
    def __init__(
        self,
        *,
        destination: _builtins.str = ...,
        connectivity: _builtins.str = ...,
        interval: _builtins.int = ...,
        samplingCount: _builtins.int = ...,
        timeout: _builtins.int = ...,
        httpMethod: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["connectivity", b"connectivity", "destination", b"destination", "httpMethod", b"httpMethod", "interval", b"interval", "samplingCount", b"samplingCount", "timeout", b"timeout"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HealthPingConfig: _TypeAlias = HealthPingConfig  # noqa: Y015
