"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from common.net import destination_pb2 as _destination_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SERVER_FIELD_NUMBER: _builtins.int
    USER_LEVEL_FIELD_NUMBER: _builtins.int
    NON_IP_QUERY_FIELD_NUMBER: _builtins.int
    BLOCK_TYPES_FIELD_NUMBER: _builtins.int
    user_level: _builtins.int
    non_IP_query: _builtins.str
    @_builtins.property
    def server(self) -> _destination_pb2.Endpoint:
        """Server is the DNS server address. If specified, this address overrides the
        original one.
        """

    @_builtins.property
    def block_types(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        server: _destination_pb2.Endpoint | None = ...,
        user_level: _builtins.int = ...,
        non_IP_query: _builtins.str = ...,
        block_types: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["server", b"server"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["block_types", b"block_types", "non_IP_query", b"non_IP_query", "server", b"server", "user_level", b"user_level"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
