"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class IPOrDomain(_message.Message):
    """Address of a network host. It may be either an IP address or a domain
    address.
    """

    DESCRIPTOR: _descriptor.Descriptor

    IP_FIELD_NUMBER: _builtins.int
    DOMAIN_FIELD_NUMBER: _builtins.int
    ip: _builtins.bytes
    """IP address. Must by either 4 or 16 bytes."""
    domain: _builtins.str
    """Domain address."""
    def __init__(
        self,
        *,
        ip: _builtins.bytes = ...,
        domain: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "domain", b"domain", "ip", b"ip"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "domain", b"domain", "ip", b"ip"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_address: _TypeAlias = _typing.Literal["ip", "domain"]  # noqa: Y015
    _WhichOneofArgType_address: _TypeAlias = _typing.Literal["address", b"address"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_address) -> _WhichOneofReturnType_address | None: ...

Global___IPOrDomain: _TypeAlias = IPOrDomain  # noqa: Y015
