"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from common.net import address_pb2 as _address_pb2
from common.net import network_pb2 as _network_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Endpoint(_message.Message):
    """Endpoint of a network connection."""

    DESCRIPTOR: _descriptor.Descriptor

    NETWORK_FIELD_NUMBER: _builtins.int
    ADDRESS_FIELD_NUMBER: _builtins.int
    PORT_FIELD_NUMBER: _builtins.int
    network: _network_pb2.Network.ValueType
    port: _builtins.int
    @_builtins.property
    def address(self) -> _address_pb2.IPOrDomain: ...
    def __init__(
        self,
        *,
        network: _network_pb2.Network.ValueType = ...,
        address: _address_pb2.IPOrDomain | None = ...,
        port: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["address", b"address"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "network", b"network", "port", b"port"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Endpoint: _TypeAlias = Endpoint  # noqa: Y015
