"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _Network:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _NetworkEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Network.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    Unknown: _Network.ValueType  # 0
    TCP: _Network.ValueType  # 2
    UDP: _Network.ValueType  # 3
    UNIX: _Network.ValueType  # 4

class Network(_Network, metaclass=_NetworkEnumTypeWrapper): ...

Unknown: Network.ValueType  # 0
TCP: Network.ValueType  # 2
UDP: Network.ValueType  # 3
UNIX: Network.ValueType  # 4
Global___Network: _TypeAlias = Network  # noqa: Y015

@_typing.final
class NetworkList(_message.Message):
    """NetworkList is a list of Networks."""

    DESCRIPTOR: _descriptor.Descriptor

    NETWORK_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def network(self) -> _containers.RepeatedScalarFieldContainer[Global___Network.ValueType]: ...
    def __init__(
        self,
        *,
        network: _abc.Iterable[Global___Network.ValueType] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["network", b"network"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___NetworkList: _TypeAlias = NetworkList  # noqa: Y015
