"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class PortRange(_message.Message):
    """PortRange represents a range of ports."""

    DESCRIPTOR: _descriptor.Descriptor

    FROM_FIELD_NUMBER: _builtins.int
    TO_FIELD_NUMBER: _builtins.int
    From: _builtins.int
    """The port that this range starts from."""
    To: _builtins.int
    """The port that this range ends with (inclusive)."""
    def __init__(
        self,
        *,
        From: _builtins.int = ...,
        To: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["From", b"From", "To", b"To"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PortRange: _TypeAlias = PortRange  # noqa: Y015

@_typing.final
class PortList(_message.Message):
    """PortList is a list of ports."""

    DESCRIPTOR: _descriptor.Descriptor

    RANGE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def range(self) -> _containers.RepeatedCompositeFieldContainer[Global___PortRange]: ...
    def __init__(
        self,
        *,
        range: _abc.Iterable[Global___PortRange] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["range", b"range"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PortList: _TypeAlias = PortList  # noqa: Y015
