"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _SecurityType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SecurityTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SecurityType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    UNKNOWN: _SecurityType.ValueType  # 0
    AUTO: _SecurityType.ValueType  # 2
    AES128_GCM: _SecurityType.ValueType  # 3
    CHACHA20_POLY1305: _SecurityType.ValueType  # 4
    NONE: _SecurityType.ValueType  # 5
    """[DEPRECATED 2023-06]"""
    ZERO: _SecurityType.ValueType  # 6

class SecurityType(_SecurityType, metaclass=_SecurityTypeEnumTypeWrapper): ...

UNKNOWN: SecurityType.ValueType  # 0
AUTO: SecurityType.ValueType  # 2
AES128_GCM: SecurityType.ValueType  # 3
CHACHA20_POLY1305: SecurityType.ValueType  # 4
NONE: SecurityType.ValueType  # 5
"""[DEPRECATED 2023-06]"""
ZERO: SecurityType.ValueType  # 6
Global___SecurityType: _TypeAlias = SecurityType  # noqa: Y015

@_typing.final
class SecurityConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    type: Global___SecurityType.ValueType
    def __init__(
        self,
        *,
        type: Global___SecurityType.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SecurityConfig: _TypeAlias = SecurityConfig  # noqa: Y015
