"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from common.net import address_pb2 as _address_pb2
from common.protocol import user_pb2 as _user_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ServerEndpoint(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: _builtins.int
    PORT_FIELD_NUMBER: _builtins.int
    USER_FIELD_NUMBER: _builtins.int
    port: _builtins.int
    @_builtins.property
    def address(self) -> _address_pb2.IPOrDomain: ...
    @_builtins.property
    def user(self) -> _user_pb2.User: ...
    def __init__(
        self,
        *,
        address: _address_pb2.IPOrDomain | None = ...,
        port: _builtins.int = ...,
        user: _user_pb2.User | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "user", b"user"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "port", b"port", "user", b"user"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ServerEndpoint: _TypeAlias = ServerEndpoint  # noqa: Y015
