"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from common.serial import typed_message_pb2 as _typed_message_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class User(_message.Message):
    """User is a generic user for all protocols."""

    DESCRIPTOR: _descriptor.Descriptor

    LEVEL_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    ACCOUNT_FIELD_NUMBER: _builtins.int
    level: _builtins.int
    email: _builtins.str
    @_builtins.property
    def account(self) -> _typed_message_pb2.TypedMessage:
        """Protocol specific account information. Must be the account proto in one of
        the proxies.
        """

    def __init__(
        self,
        *,
        level: _builtins.int = ...,
        email: _builtins.str = ...,
        account: _typed_message_pb2.TypedMessage | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["account", b"account"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["account", b"account", "email", b"email", "level", b"level"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___User: _TypeAlias = User  # noqa: Y015
