"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class MasqStringHeadersEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    VERSION_FIELD_NUMBER: _builtins.int
    AUTH_FIELD_NUMBER: _builtins.int
    UDP_IDLE_TIMEOUT_FIELD_NUMBER: _builtins.int
    MASQ_TYPE_FIELD_NUMBER: _builtins.int
    MASQ_FILE_FIELD_NUMBER: _builtins.int
    MASQ_URL_FIELD_NUMBER: _builtins.int
    MASQ_URL_REWRITE_HOST_FIELD_NUMBER: _builtins.int
    MASQ_URL_INSECURE_FIELD_NUMBER: _builtins.int
    MASQ_STRING_FIELD_NUMBER: _builtins.int
    MASQ_STRING_HEADERS_FIELD_NUMBER: _builtins.int
    MASQ_STRING_STATUS_CODE_FIELD_NUMBER: _builtins.int
    version: _builtins.int
    auth: _builtins.str
    udp_idle_timeout: _builtins.int
    masq_type: _builtins.str
    masq_file: _builtins.str
    masq_url: _builtins.str
    masq_url_rewrite_host: _builtins.bool
    masq_url_insecure: _builtins.bool
    masq_string: _builtins.str
    masq_string_status_code: _builtins.int
    @_builtins.property
    def masq_string_headers(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        version: _builtins.int = ...,
        auth: _builtins.str = ...,
        udp_idle_timeout: _builtins.int = ...,
        masq_type: _builtins.str = ...,
        masq_file: _builtins.str = ...,
        masq_url: _builtins.str = ...,
        masq_url_rewrite_host: _builtins.bool = ...,
        masq_url_insecure: _builtins.bool = ...,
        masq_string: _builtins.str = ...,
        masq_string_headers: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        masq_string_status_code: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["auth", b"auth", "masq_file", b"masq_file", "masq_string", b"masq_string", "masq_string_headers", b"masq_string_headers", "masq_string_status_code", b"masq_string_status_code", "masq_type", b"masq_type", "masq_url", b"masq_url", "masq_url_insecure", b"masq_url_insecure", "masq_url_rewrite_host", b"masq_url_rewrite_host", "udp_idle_timeout", b"udp_idle_timeout", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
