# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/hysteria/config.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'transport/internet/hysteria/config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(transport/internet/hysteria/config.proto\x12 xray.transport.internet.hysteria\"\x81\x03\n\x06\x43onfig\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0c\n\x04\x61uth\x18\x02 \x01(\t\x12\x18\n\x10udp_idle_timeout\x18\x03 \x01(\x03\x12\x11\n\tmasq_type\x18\x04 \x01(\t\x12\x11\n\tmasq_file\x18\x05 \x01(\t\x12\x10\n\x08masq_url\x18\x06 \x01(\t\x12\x1d\n\x15masq_url_rewrite_host\x18\x07 \x01(\x08\x12\x19\n\x11masq_url_insecure\x18\x08 \x01(\x08\x12\x13\n\x0bmasq_string\x18\t \x01(\t\x12\\\n\x13masq_string_headers\x18\n \x03(\x0b\x32?.xray.transport.internet.hysteria.Config.MasqStringHeadersEntry\x12\x1f\n\x17masq_string_status_code\x18\x0b \x01(\x05\x1a\x38\n\x16MasqStringHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x82\x01\n$com.xray.transport.internet.hysteriaP\x01Z5github.com/xtls/xray-core/transport/internet/hysteria\xaa\x02 Xray.Transport.Internet.Hysteriab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.hysteria.config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.xray.transport.internet.hysteriaP\001Z5github.com/xtls/xray-core/transport/internet/hysteria\252\002 Xray.Transport.Internet.Hysteria'
  _globals['_CONFIG_MASQSTRINGHEADERSENTRY']._loaded_options = None
  _globals['_CONFIG_MASQSTRINGHEADERSENTRY']._serialized_options = b'8\001'
  _globals['_CONFIG']._serialized_start=79
  _globals['_CONFIG']._serialized_end=464
  _globals['_CONFIG_MASQSTRINGHEADERSENTRY']._serialized_start=408
  _globals['_CONFIG_MASQSTRINGHEADERSENTRY']._serialized_end=464
# @@protoc_insertion_point(module_scope)
