"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PACKETS_FROM_FIELD_NUMBER: _builtins.int
    PACKETS_TO_FIELD_NUMBER: _builtins.int
    LENGTH_MIN_FIELD_NUMBER: _builtins.int
    LENGTH_MAX_FIELD_NUMBER: _builtins.int
    DELAY_MIN_FIELD_NUMBER: _builtins.int
    DELAY_MAX_FIELD_NUMBER: _builtins.int
    MAX_SPLIT_MIN_FIELD_NUMBER: _builtins.int
    MAX_SPLIT_MAX_FIELD_NUMBER: _builtins.int
    packets_from: _builtins.int
    packets_to: _builtins.int
    length_min: _builtins.int
    length_max: _builtins.int
    delay_min: _builtins.int
    delay_max: _builtins.int
    max_split_min: _builtins.int
    max_split_max: _builtins.int
    def __init__(
        self,
        *,
        packets_from: _builtins.int = ...,
        packets_to: _builtins.int = ...,
        length_min: _builtins.int = ...,
        length_max: _builtins.int = ...,
        delay_min: _builtins.int = ...,
        delay_max: _builtins.int = ...,
        max_split_min: _builtins.int = ...,
        max_split_max: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["delay_max", b"delay_max", "delay_min", b"delay_min", "length_max", b"length_max", "length_min", b"length_min", "max_split_max", b"max_split_max", "max_split_min", b"max_split_min", "packets_from", b"packets_from", "packets_to", b"packets_to"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
