# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/finalmask/fragment/config.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'transport/internet/finalmask/fragment/config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2transport/internet/finalmask/fragment/config.proto\x12*xray.transport.internet.finalmask.fragment\"\xae\x01\n\x06\x43onfig\x12\x14\n\x0cpackets_from\x18\x01 \x01(\x03\x12\x12\n\npackets_to\x18\x02 \x01(\x03\x12\x12\n\nlength_min\x18\x03 \x01(\x03\x12\x12\n\nlength_max\x18\x04 \x01(\x03\x12\x11\n\tdelay_min\x18\x05 \x01(\x03\x12\x11\n\tdelay_max\x18\x06 \x01(\x03\x12\x15\n\rmax_split_min\x18\x07 \x01(\x03\x12\x15\n\rmax_split_max\x18\x08 \x01(\x03\x42\xa0\x01\n.com.xray.transport.internet.finalmask.fragmentP\x01Z?github.com/xtls/xray-core/transport/internet/finalmask/fragment\xaa\x02*Xray.Transport.Internet.Finalmask.Fragmentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.finalmask.fragment.config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n.com.xray.transport.internet.finalmask.fragmentP\001Z?github.com/xtls/xray-core/transport/internet/finalmask/fragment\252\002*Xray.Transport.Internet.Finalmask.Fragment'
  _globals['_CONFIG']._serialized_start=99
  _globals['_CONFIG']._serialized_end=273
# @@protoc_insertion_point(module_scope)
