"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetStatsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    RESET_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """Name of the stat counter."""
    reset: _builtins.bool
    """Whether or not to reset the counter to fetching its value."""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        reset: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "reset", b"reset"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetStatsRequest: _TypeAlias = GetStatsRequest  # noqa: Y015

@_typing.final
class Stat(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    value: _builtins.int
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Stat: _TypeAlias = Stat  # noqa: Y015

@_typing.final
class GetStatsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STAT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def stat(self) -> Global___Stat: ...
    def __init__(
        self,
        *,
        stat: Global___Stat | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stat", b"stat"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stat", b"stat"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetStatsResponse: _TypeAlias = GetStatsResponse  # noqa: Y015

@_typing.final
class QueryStatsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PATTERN_FIELD_NUMBER: _builtins.int
    RESET_FIELD_NUMBER: _builtins.int
    pattern: _builtins.str
    reset: _builtins.bool
    def __init__(
        self,
        *,
        pattern: _builtins.str = ...,
        reset: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pattern", b"pattern", "reset", b"reset"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___QueryStatsRequest: _TypeAlias = QueryStatsRequest  # noqa: Y015

@_typing.final
class QueryStatsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STAT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def stat(self) -> _containers.RepeatedCompositeFieldContainer[Global___Stat]: ...
    def __init__(
        self,
        *,
        stat: _abc.Iterable[Global___Stat] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stat", b"stat"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___QueryStatsResponse: _TypeAlias = QueryStatsResponse  # noqa: Y015

@_typing.final
class SysStatsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SysStatsRequest: _TypeAlias = SysStatsRequest  # noqa: Y015

@_typing.final
class SysStatsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NUMGOROUTINE_FIELD_NUMBER: _builtins.int
    NUMGC_FIELD_NUMBER: _builtins.int
    ALLOC_FIELD_NUMBER: _builtins.int
    TOTALALLOC_FIELD_NUMBER: _builtins.int
    SYS_FIELD_NUMBER: _builtins.int
    MALLOCS_FIELD_NUMBER: _builtins.int
    FREES_FIELD_NUMBER: _builtins.int
    LIVEOBJECTS_FIELD_NUMBER: _builtins.int
    PAUSETOTALNS_FIELD_NUMBER: _builtins.int
    UPTIME_FIELD_NUMBER: _builtins.int
    NumGoroutine: _builtins.int
    NumGC: _builtins.int
    Alloc: _builtins.int
    TotalAlloc: _builtins.int
    Sys: _builtins.int
    Mallocs: _builtins.int
    Frees: _builtins.int
    LiveObjects: _builtins.int
    PauseTotalNs: _builtins.int
    Uptime: _builtins.int
    def __init__(
        self,
        *,
        NumGoroutine: _builtins.int = ...,
        NumGC: _builtins.int = ...,
        Alloc: _builtins.int = ...,
        TotalAlloc: _builtins.int = ...,
        Sys: _builtins.int = ...,
        Mallocs: _builtins.int = ...,
        Frees: _builtins.int = ...,
        LiveObjects: _builtins.int = ...,
        PauseTotalNs: _builtins.int = ...,
        Uptime: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["Alloc", b"Alloc", "Frees", b"Frees", "LiveObjects", b"LiveObjects", "Mallocs", b"Mallocs", "NumGC", b"NumGC", "NumGoroutine", b"NumGoroutine", "PauseTotalNs", b"PauseTotalNs", "Sys", b"Sys", "TotalAlloc", b"TotalAlloc", "Uptime", b"Uptime"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SysStatsResponse: _TypeAlias = SysStatsResponse  # noqa: Y015

@_typing.final
class GetStatsOnlineIpListResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class IpsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.int
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    NAME_FIELD_NUMBER: _builtins.int
    IPS_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    @_builtins.property
    def ips(self) -> _containers.ScalarMap[_builtins.str, _builtins.int]: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        ips: _abc.Mapping[_builtins.str, _builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ips", b"ips", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetStatsOnlineIpListResponse: _TypeAlias = GetStatsOnlineIpListResponse  # noqa: Y015

@_typing.final
class GetAllOnlineUsersRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetAllOnlineUsersRequest: _TypeAlias = GetAllOnlineUsersRequest  # noqa: Y015

@_typing.final
class GetAllOnlineUsersResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def users(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        users: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["users", b"users"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetAllOnlineUsersResponse: _TypeAlias = GetAllOnlineUsersResponse  # noqa: Y015

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
