"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from app.stats.command import command_pb2 as _command_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class StatsServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> StatsServiceAsyncStub: ...
    GetStats: _grpc.UnaryUnaryMultiCallable[_command_pb2.GetStatsRequest, _command_pb2.GetStatsResponse]
    GetStatsOnline: _grpc.UnaryUnaryMultiCallable[_command_pb2.GetStatsRequest, _command_pb2.GetStatsResponse]
    QueryStats: _grpc.UnaryUnaryMultiCallable[_command_pb2.QueryStatsRequest, _command_pb2.QueryStatsResponse]
    GetSysStats: _grpc.UnaryUnaryMultiCallable[_command_pb2.SysStatsRequest, _command_pb2.SysStatsResponse]
    GetStatsOnlineIpList: _grpc.UnaryUnaryMultiCallable[_command_pb2.GetStatsRequest, _command_pb2.GetStatsOnlineIpListResponse]
    GetAllOnlineUsers: _grpc.UnaryUnaryMultiCallable[_command_pb2.GetAllOnlineUsersRequest, _command_pb2.GetAllOnlineUsersResponse]

@_typing.type_check_only
class StatsServiceAsyncStub(StatsServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    GetStats: _aio.UnaryUnaryMultiCallable[_command_pb2.GetStatsRequest, _command_pb2.GetStatsResponse]  # type: ignore[assignment]
    GetStatsOnline: _aio.UnaryUnaryMultiCallable[_command_pb2.GetStatsRequest, _command_pb2.GetStatsResponse]  # type: ignore[assignment]
    QueryStats: _aio.UnaryUnaryMultiCallable[_command_pb2.QueryStatsRequest, _command_pb2.QueryStatsResponse]  # type: ignore[assignment]
    GetSysStats: _aio.UnaryUnaryMultiCallable[_command_pb2.SysStatsRequest, _command_pb2.SysStatsResponse]  # type: ignore[assignment]
    GetStatsOnlineIpList: _aio.UnaryUnaryMultiCallable[_command_pb2.GetStatsRequest, _command_pb2.GetStatsOnlineIpListResponse]  # type: ignore[assignment]
    GetAllOnlineUsers: _aio.UnaryUnaryMultiCallable[_command_pb2.GetAllOnlineUsersRequest, _command_pb2.GetAllOnlineUsersResponse]  # type: ignore[assignment]

class StatsServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def GetStats(
        self,
        request: _command_pb2.GetStatsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.GetStatsResponse, _abc.Awaitable[_command_pb2.GetStatsResponse]]: ...

    @_abc_1.abstractmethod
    def GetStatsOnline(
        self,
        request: _command_pb2.GetStatsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.GetStatsResponse, _abc.Awaitable[_command_pb2.GetStatsResponse]]: ...

    @_abc_1.abstractmethod
    def QueryStats(
        self,
        request: _command_pb2.QueryStatsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.QueryStatsResponse, _abc.Awaitable[_command_pb2.QueryStatsResponse]]: ...

    @_abc_1.abstractmethod
    def GetSysStats(
        self,
        request: _command_pb2.SysStatsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.SysStatsResponse, _abc.Awaitable[_command_pb2.SysStatsResponse]]: ...

    @_abc_1.abstractmethod
    def GetStatsOnlineIpList(
        self,
        request: _command_pb2.GetStatsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.GetStatsOnlineIpListResponse, _abc.Awaitable[_command_pb2.GetStatsOnlineIpListResponse]]: ...

    @_abc_1.abstractmethod
    def GetAllOnlineUsers(
        self,
        request: _command_pb2.GetAllOnlineUsersRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.GetAllOnlineUsersResponse, _abc.Awaitable[_command_pb2.GetAllOnlineUsersResponse]]: ...

def add_StatsServiceServicer_to_server(servicer: StatsServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
