"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from common.net import network_pb2 as _network_pb2
from common.net import port_pb2 as _port_pb2
from common.serial import typed_message_pb2 as _typed_message_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Domain(_message.Message):
    """Domain for routing decision."""

    DESCRIPTOR: _descriptor.Descriptor

    class _Type:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Domain._Type.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        Plain: Domain._Type.ValueType  # 0
        """The value is used as is."""
        Regex: Domain._Type.ValueType  # 1
        """The value is used as a regular expression."""
        Domain: Domain._Type.ValueType  # 2
        """The value is a root domain."""
        Full: Domain._Type.ValueType  # 3
        """The value is a domain."""

    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        """Type of domain value."""

    Plain: Domain.Type.ValueType  # 0
    """The value is used as is."""
    Regex: Domain.Type.ValueType  # 1
    """The value is used as a regular expression."""
    Domain: Domain.Type.ValueType  # 2
    """The value is a root domain."""
    Full: Domain.Type.ValueType  # 3
    """The value is a domain."""

    @_typing.final
    class Attribute(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        BOOL_VALUE_FIELD_NUMBER: _builtins.int
        INT_VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        bool_value: _builtins.bool
        int_value: _builtins.int
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            bool_value: _builtins.bool = ...,
            int_value: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["bool_value", b"bool_value", "int_value", b"int_value", "typed_value", b"typed_value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bool_value", b"bool_value", "int_value", b"int_value", "key", b"key", "typed_value", b"typed_value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_typed_value: _TypeAlias = _typing.Literal["bool_value", "int_value"]  # noqa: Y015
        _WhichOneofArgType_typed_value: _TypeAlias = _typing.Literal["typed_value", b"typed_value"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_typed_value) -> _WhichOneofReturnType_typed_value | None: ...

    TYPE_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    ATTRIBUTE_FIELD_NUMBER: _builtins.int
    type: Global___Domain.Type.ValueType
    """Domain matching type."""
    value: _builtins.str
    """Domain value."""
    @_builtins.property
    def attribute(self) -> _containers.RepeatedCompositeFieldContainer[Global___Domain.Attribute]:
        """Attributes of this domain. May be used for filtering."""

    def __init__(
        self,
        *,
        type: Global___Domain.Type.ValueType = ...,
        value: _builtins.str = ...,
        attribute: _abc.Iterable[Global___Domain.Attribute] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attribute", b"attribute", "type", b"type", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Domain: _TypeAlias = Domain  # noqa: Y015

@_typing.final
class CIDR(_message.Message):
    """IP for routing decision, in CIDR form."""

    DESCRIPTOR: _descriptor.Descriptor

    IP_FIELD_NUMBER: _builtins.int
    PREFIX_FIELD_NUMBER: _builtins.int
    ip: _builtins.bytes
    """IP address, should be either 4 or 16 bytes."""
    prefix: _builtins.int
    """Number of leading ones in the network mask."""
    def __init__(
        self,
        *,
        ip: _builtins.bytes = ...,
        prefix: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ip", b"ip", "prefix", b"prefix"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CIDR: _TypeAlias = CIDR  # noqa: Y015

@_typing.final
class GeoIP(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COUNTRY_CODE_FIELD_NUMBER: _builtins.int
    CIDR_FIELD_NUMBER: _builtins.int
    REVERSE_MATCH_FIELD_NUMBER: _builtins.int
    country_code: _builtins.str
    reverse_match: _builtins.bool
    @_builtins.property
    def cidr(self) -> _containers.RepeatedCompositeFieldContainer[Global___CIDR]: ...
    def __init__(
        self,
        *,
        country_code: _builtins.str = ...,
        cidr: _abc.Iterable[Global___CIDR] | None = ...,
        reverse_match: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cidr", b"cidr", "country_code", b"country_code", "reverse_match", b"reverse_match"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GeoIP: _TypeAlias = GeoIP  # noqa: Y015

@_typing.final
class GeoIPList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENTRY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def entry(self) -> _containers.RepeatedCompositeFieldContainer[Global___GeoIP]: ...
    def __init__(
        self,
        *,
        entry: _abc.Iterable[Global___GeoIP] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry", b"entry"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GeoIPList: _TypeAlias = GeoIPList  # noqa: Y015

@_typing.final
class GeoSite(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COUNTRY_CODE_FIELD_NUMBER: _builtins.int
    DOMAIN_FIELD_NUMBER: _builtins.int
    country_code: _builtins.str
    @_builtins.property
    def domain(self) -> _containers.RepeatedCompositeFieldContainer[Global___Domain]: ...
    def __init__(
        self,
        *,
        country_code: _builtins.str = ...,
        domain: _abc.Iterable[Global___Domain] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["country_code", b"country_code", "domain", b"domain"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GeoSite: _TypeAlias = GeoSite  # noqa: Y015

@_typing.final
class GeoSiteList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENTRY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def entry(self) -> _containers.RepeatedCompositeFieldContainer[Global___GeoSite]: ...
    def __init__(
        self,
        *,
        entry: _abc.Iterable[Global___GeoSite] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry", b"entry"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GeoSiteList: _TypeAlias = GeoSiteList  # noqa: Y015

@_typing.final
class RoutingRule(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class AttributesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    TAG_FIELD_NUMBER: _builtins.int
    BALANCING_TAG_FIELD_NUMBER: _builtins.int
    RULE_TAG_FIELD_NUMBER: _builtins.int
    DOMAIN_FIELD_NUMBER: _builtins.int
    GEOIP_FIELD_NUMBER: _builtins.int
    PORT_LIST_FIELD_NUMBER: _builtins.int
    NETWORKS_FIELD_NUMBER: _builtins.int
    SOURCE_GEOIP_FIELD_NUMBER: _builtins.int
    SOURCE_PORT_LIST_FIELD_NUMBER: _builtins.int
    USER_EMAIL_FIELD_NUMBER: _builtins.int
    INBOUND_TAG_FIELD_NUMBER: _builtins.int
    PROTOCOL_FIELD_NUMBER: _builtins.int
    ATTRIBUTES_FIELD_NUMBER: _builtins.int
    LOCAL_GEOIP_FIELD_NUMBER: _builtins.int
    LOCAL_PORT_LIST_FIELD_NUMBER: _builtins.int
    VLESS_ROUTE_LIST_FIELD_NUMBER: _builtins.int
    PROCESS_FIELD_NUMBER: _builtins.int
    WEBHOOK_FIELD_NUMBER: _builtins.int
    tag: _builtins.str
    """Tag of outbound that this rule is pointing to."""
    balancing_tag: _builtins.str
    """Tag of routing balancer."""
    rule_tag: _builtins.str
    @_builtins.property
    def domain(self) -> _containers.RepeatedCompositeFieldContainer[Global___Domain]:
        """List of domains for target domain matching."""

    @_builtins.property
    def geoip(self) -> _containers.RepeatedCompositeFieldContainer[Global___GeoIP]:
        """List of GeoIPs for target IP address matching. If this entry exists, the
        cidr above will have no effect. GeoIP fields with the same country code are
        supposed to contain exactly same content. They will be merged during
        runtime. For customized GeoIPs, please leave country code empty.
        """

    @_builtins.property
    def port_list(self) -> _port_pb2.PortList:
        """List of ports."""

    @_builtins.property
    def networks(self) -> _containers.RepeatedScalarFieldContainer[_network_pb2.Network.ValueType]:
        """List of networks for matching."""

    @_builtins.property
    def source_geoip(self) -> _containers.RepeatedCompositeFieldContainer[Global___GeoIP]:
        """List of GeoIPs for source IP address matching. If this entry exists, the
        source_cidr above will have no effect.
        """

    @_builtins.property
    def source_port_list(self) -> _port_pb2.PortList:
        """List of ports for source port matching."""

    @_builtins.property
    def user_email(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def inbound_tag(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def protocol(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def attributes(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def local_geoip(self) -> _containers.RepeatedCompositeFieldContainer[Global___GeoIP]: ...
    @_builtins.property
    def local_port_list(self) -> _port_pb2.PortList: ...
    @_builtins.property
    def vless_route_list(self) -> _port_pb2.PortList: ...
    @_builtins.property
    def process(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def webhook(self) -> Global___WebhookConfig: ...
    def __init__(
        self,
        *,
        tag: _builtins.str = ...,
        balancing_tag: _builtins.str = ...,
        rule_tag: _builtins.str = ...,
        domain: _abc.Iterable[Global___Domain] | None = ...,
        geoip: _abc.Iterable[Global___GeoIP] | None = ...,
        port_list: _port_pb2.PortList | None = ...,
        networks: _abc.Iterable[_network_pb2.Network.ValueType] | None = ...,
        source_geoip: _abc.Iterable[Global___GeoIP] | None = ...,
        source_port_list: _port_pb2.PortList | None = ...,
        user_email: _abc.Iterable[_builtins.str] | None = ...,
        inbound_tag: _abc.Iterable[_builtins.str] | None = ...,
        protocol: _abc.Iterable[_builtins.str] | None = ...,
        attributes: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        local_geoip: _abc.Iterable[Global___GeoIP] | None = ...,
        local_port_list: _port_pb2.PortList | None = ...,
        vless_route_list: _port_pb2.PortList | None = ...,
        process: _abc.Iterable[_builtins.str] | None = ...,
        webhook: Global___WebhookConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["balancing_tag", b"balancing_tag", "local_port_list", b"local_port_list", "port_list", b"port_list", "source_port_list", b"source_port_list", "tag", b"tag", "target_tag", b"target_tag", "vless_route_list", b"vless_route_list", "webhook", b"webhook"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attributes", b"attributes", "balancing_tag", b"balancing_tag", "domain", b"domain", "geoip", b"geoip", "inbound_tag", b"inbound_tag", "local_geoip", b"local_geoip", "local_port_list", b"local_port_list", "networks", b"networks", "port_list", b"port_list", "process", b"process", "protocol", b"protocol", "rule_tag", b"rule_tag", "source_geoip", b"source_geoip", "source_port_list", b"source_port_list", "tag", b"tag", "target_tag", b"target_tag", "user_email", b"user_email", "vless_route_list", b"vless_route_list", "webhook", b"webhook"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_target_tag: _TypeAlias = _typing.Literal["tag", "balancing_tag"]  # noqa: Y015
    _WhichOneofArgType_target_tag: _TypeAlias = _typing.Literal["target_tag", b"target_tag"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_target_tag) -> _WhichOneofReturnType_target_tag | None: ...

Global___RoutingRule: _TypeAlias = RoutingRule  # noqa: Y015

@_typing.final
class WebhookConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class HeadersEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    URL_FIELD_NUMBER: _builtins.int
    DEDUPLICATION_FIELD_NUMBER: _builtins.int
    HEADERS_FIELD_NUMBER: _builtins.int
    url: _builtins.str
    deduplication: _builtins.int
    @_builtins.property
    def headers(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        url: _builtins.str = ...,
        deduplication: _builtins.int = ...,
        headers: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["deduplication", b"deduplication", "headers", b"headers", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WebhookConfig: _TypeAlias = WebhookConfig  # noqa: Y015

@_typing.final
class BalancingRule(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    OUTBOUND_SELECTOR_FIELD_NUMBER: _builtins.int
    STRATEGY_FIELD_NUMBER: _builtins.int
    STRATEGY_SETTINGS_FIELD_NUMBER: _builtins.int
    FALLBACK_TAG_FIELD_NUMBER: _builtins.int
    tag: _builtins.str
    strategy: _builtins.str
    fallback_tag: _builtins.str
    @_builtins.property
    def outbound_selector(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def strategy_settings(self) -> _typed_message_pb2.TypedMessage: ...
    def __init__(
        self,
        *,
        tag: _builtins.str = ...,
        outbound_selector: _abc.Iterable[_builtins.str] | None = ...,
        strategy: _builtins.str = ...,
        strategy_settings: _typed_message_pb2.TypedMessage | None = ...,
        fallback_tag: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["strategy_settings", b"strategy_settings"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fallback_tag", b"fallback_tag", "outbound_selector", b"outbound_selector", "strategy", b"strategy", "strategy_settings", b"strategy_settings", "tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BalancingRule: _TypeAlias = BalancingRule  # noqa: Y015

@_typing.final
class StrategyWeight(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REGEXP_FIELD_NUMBER: _builtins.int
    MATCH_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    regexp: _builtins.bool
    match: _builtins.str
    value: _builtins.float
    def __init__(
        self,
        *,
        regexp: _builtins.bool = ...,
        match: _builtins.str = ...,
        value: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["match", b"match", "regexp", b"regexp", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StrategyWeight: _TypeAlias = StrategyWeight  # noqa: Y015

@_typing.final
class StrategyLeastLoadConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COSTS_FIELD_NUMBER: _builtins.int
    BASELINES_FIELD_NUMBER: _builtins.int
    EXPECTED_FIELD_NUMBER: _builtins.int
    MAXRTT_FIELD_NUMBER: _builtins.int
    TOLERANCE_FIELD_NUMBER: _builtins.int
    expected: _builtins.int
    """expected nodes count to select"""
    maxRTT: _builtins.int
    """max acceptable rtt, filter away high delay nodes. default 0"""
    tolerance: _builtins.float
    """acceptable failure rate"""
    @_builtins.property
    def costs(self) -> _containers.RepeatedCompositeFieldContainer[Global___StrategyWeight]:
        """weight settings"""

    @_builtins.property
    def baselines(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """RTT baselines for selecting, int64 values of time.Duration"""

    def __init__(
        self,
        *,
        costs: _abc.Iterable[Global___StrategyWeight] | None = ...,
        baselines: _abc.Iterable[_builtins.int] | None = ...,
        expected: _builtins.int = ...,
        maxRTT: _builtins.int = ...,
        tolerance: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["baselines", b"baselines", "costs", b"costs", "expected", b"expected", "maxRTT", b"maxRTT", "tolerance", b"tolerance"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StrategyLeastLoadConfig: _TypeAlias = StrategyLeastLoadConfig  # noqa: Y015

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _DomainStrategy:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _DomainStrategyEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Config._DomainStrategy.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        AsIs: Config._DomainStrategy.ValueType  # 0
        """Use domain as is."""
        IpIfNonMatch: Config._DomainStrategy.ValueType  # 2
        """[Deprecated] Always resolve IP for domains.
        UseIp = 1;

        Resolve to IP if the domain doesn't match any rules.
        """
        IpOnDemand: Config._DomainStrategy.ValueType  # 3
        """Resolve to IP if any rule requires IP matching."""

    class DomainStrategy(_DomainStrategy, metaclass=_DomainStrategyEnumTypeWrapper): ...
    AsIs: Config.DomainStrategy.ValueType  # 0
    """Use domain as is."""
    IpIfNonMatch: Config.DomainStrategy.ValueType  # 2
    """[Deprecated] Always resolve IP for domains.
    UseIp = 1;

    Resolve to IP if the domain doesn't match any rules.
    """
    IpOnDemand: Config.DomainStrategy.ValueType  # 3
    """Resolve to IP if any rule requires IP matching."""

    DOMAIN_STRATEGY_FIELD_NUMBER: _builtins.int
    RULE_FIELD_NUMBER: _builtins.int
    BALANCING_RULE_FIELD_NUMBER: _builtins.int
    domain_strategy: Global___Config.DomainStrategy.ValueType
    @_builtins.property
    def rule(self) -> _containers.RepeatedCompositeFieldContainer[Global___RoutingRule]: ...
    @_builtins.property
    def balancing_rule(self) -> _containers.RepeatedCompositeFieldContainer[Global___BalancingRule]: ...
    def __init__(
        self,
        *,
        domain_strategy: Global___Config.DomainStrategy.ValueType = ...,
        rule: _abc.Iterable[Global___RoutingRule] | None = ...,
        balancing_rule: _abc.Iterable[Global___BalancingRule] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["balancing_rule", b"balancing_rule", "domain_strategy", b"domain_strategy", "rule", b"rule"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
