"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class PeerConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PUBLIC_KEY_FIELD_NUMBER: _builtins.int
    PRE_SHARED_KEY_FIELD_NUMBER: _builtins.int
    ENDPOINT_FIELD_NUMBER: _builtins.int
    KEEP_ALIVE_FIELD_NUMBER: _builtins.int
    ALLOWED_IPS_FIELD_NUMBER: _builtins.int
    public_key: _builtins.str
    pre_shared_key: _builtins.str
    endpoint: _builtins.str
    keep_alive: _builtins.int
    @_builtins.property
    def allowed_ips(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        public_key: _builtins.str = ...,
        pre_shared_key: _builtins.str = ...,
        endpoint: _builtins.str = ...,
        keep_alive: _builtins.int = ...,
        allowed_ips: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allowed_ips", b"allowed_ips", "endpoint", b"endpoint", "keep_alive", b"keep_alive", "pre_shared_key", b"pre_shared_key", "public_key", b"public_key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PeerConfig: _TypeAlias = PeerConfig  # noqa: Y015

@_typing.final
class DeviceConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _DomainStrategy:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _DomainStrategyEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DeviceConfig._DomainStrategy.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        FORCE_IP: DeviceConfig._DomainStrategy.ValueType  # 0
        FORCE_IP4: DeviceConfig._DomainStrategy.ValueType  # 1
        FORCE_IP6: DeviceConfig._DomainStrategy.ValueType  # 2
        FORCE_IP46: DeviceConfig._DomainStrategy.ValueType  # 3
        FORCE_IP64: DeviceConfig._DomainStrategy.ValueType  # 4

    class DomainStrategy(_DomainStrategy, metaclass=_DomainStrategyEnumTypeWrapper): ...
    FORCE_IP: DeviceConfig.DomainStrategy.ValueType  # 0
    FORCE_IP4: DeviceConfig.DomainStrategy.ValueType  # 1
    FORCE_IP6: DeviceConfig.DomainStrategy.ValueType  # 2
    FORCE_IP46: DeviceConfig.DomainStrategy.ValueType  # 3
    FORCE_IP64: DeviceConfig.DomainStrategy.ValueType  # 4

    SECRET_KEY_FIELD_NUMBER: _builtins.int
    ENDPOINT_FIELD_NUMBER: _builtins.int
    PEERS_FIELD_NUMBER: _builtins.int
    MTU_FIELD_NUMBER: _builtins.int
    NUM_WORKERS_FIELD_NUMBER: _builtins.int
    RESERVED_FIELD_NUMBER: _builtins.int
    DOMAIN_STRATEGY_FIELD_NUMBER: _builtins.int
    IS_CLIENT_FIELD_NUMBER: _builtins.int
    NO_KERNEL_TUN_FIELD_NUMBER: _builtins.int
    secret_key: _builtins.str
    mtu: _builtins.int
    num_workers: _builtins.int
    reserved: _builtins.bytes
    domain_strategy: Global___DeviceConfig.DomainStrategy.ValueType
    is_client: _builtins.bool
    no_kernel_tun: _builtins.bool
    @_builtins.property
    def endpoint(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def peers(self) -> _containers.RepeatedCompositeFieldContainer[Global___PeerConfig]: ...
    def __init__(
        self,
        *,
        secret_key: _builtins.str = ...,
        endpoint: _abc.Iterable[_builtins.str] | None = ...,
        peers: _abc.Iterable[Global___PeerConfig] | None = ...,
        mtu: _builtins.int = ...,
        num_workers: _builtins.int = ...,
        reserved: _builtins.bytes = ...,
        domain_strategy: Global___DeviceConfig.DomainStrategy.ValueType = ...,
        is_client: _builtins.bool = ...,
        no_kernel_tun: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["domain_strategy", b"domain_strategy", "endpoint", b"endpoint", "is_client", b"is_client", "mtu", b"mtu", "no_kernel_tun", b"no_kernel_tun", "num_workers", b"num_workers", "peers", b"peers", "reserved", b"reserved", "secret_key", b"secret_key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeviceConfig: _TypeAlias = DeviceConfig  # noqa: Y015
