"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from transport.internet.grpc.encoding import stream_pb2 as _stream_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class GRPCServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> GRPCServiceAsyncStub: ...
    Tun: _grpc.StreamStreamMultiCallable[_stream_pb2.Hunk, _stream_pb2.Hunk]
    TunMulti: _grpc.StreamStreamMultiCallable[_stream_pb2.MultiHunk, _stream_pb2.MultiHunk]

@_typing.type_check_only
class GRPCServiceAsyncStub(GRPCServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Tun: _aio.StreamStreamMultiCallable[_stream_pb2.Hunk, _stream_pb2.Hunk]  # type: ignore[assignment]
    TunMulti: _aio.StreamStreamMultiCallable[_stream_pb2.MultiHunk, _stream_pb2.MultiHunk]  # type: ignore[assignment]

class GRPCServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Tun(
        self,
        request_iterator: _MaybeAsyncIterator[_stream_pb2.Hunk],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_stream_pb2.Hunk], _abc.AsyncIterator[_stream_pb2.Hunk]]: ...

    @_abc_1.abstractmethod
    def TunMulti(
        self,
        request_iterator: _MaybeAsyncIterator[_stream_pb2.MultiHunk],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_stream_pb2.MultiHunk], _abc.AsyncIterator[_stream_pb2.MultiHunk]]: ...

def add_GRPCServiceServicer_to_server(servicer: GRPCServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
