"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from common.protocol import user_pb2 as _user_pb2
from common.serial import typed_message_pb2 as _typed_message_pb2
from core import config_pb2 as _config_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AddUserOperation(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def user(self) -> _user_pb2.User: ...
    def __init__(
        self,
        *,
        user: _user_pb2.User | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["user", b"user"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["user", b"user"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddUserOperation: _TypeAlias = AddUserOperation  # noqa: Y015

@_typing.final
class RemoveUserOperation(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EMAIL_FIELD_NUMBER: _builtins.int
    email: _builtins.str
    def __init__(
        self,
        *,
        email: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["email", b"email"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RemoveUserOperation: _TypeAlias = RemoveUserOperation  # noqa: Y015

@_typing.final
class AddInboundRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INBOUND_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def inbound(self) -> _config_pb2.InboundHandlerConfig: ...
    def __init__(
        self,
        *,
        inbound: _config_pb2.InboundHandlerConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["inbound", b"inbound"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["inbound", b"inbound"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddInboundRequest: _TypeAlias = AddInboundRequest  # noqa: Y015

@_typing.final
class AddInboundResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddInboundResponse: _TypeAlias = AddInboundResponse  # noqa: Y015

@_typing.final
class RemoveInboundRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    tag: _builtins.str
    def __init__(
        self,
        *,
        tag: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RemoveInboundRequest: _TypeAlias = RemoveInboundRequest  # noqa: Y015

@_typing.final
class RemoveInboundResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RemoveInboundResponse: _TypeAlias = RemoveInboundResponse  # noqa: Y015

@_typing.final
class AlterInboundRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    OPERATION_FIELD_NUMBER: _builtins.int
    tag: _builtins.str
    @_builtins.property
    def operation(self) -> _typed_message_pb2.TypedMessage: ...
    def __init__(
        self,
        *,
        tag: _builtins.str = ...,
        operation: _typed_message_pb2.TypedMessage | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["operation", b"operation"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["operation", b"operation", "tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AlterInboundRequest: _TypeAlias = AlterInboundRequest  # noqa: Y015

@_typing.final
class AlterInboundResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AlterInboundResponse: _TypeAlias = AlterInboundResponse  # noqa: Y015

@_typing.final
class ListInboundsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ISONLYTAGS_FIELD_NUMBER: _builtins.int
    isOnlyTags: _builtins.bool
    def __init__(
        self,
        *,
        isOnlyTags: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["isOnlyTags", b"isOnlyTags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListInboundsRequest: _TypeAlias = ListInboundsRequest  # noqa: Y015

@_typing.final
class ListInboundsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INBOUNDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def inbounds(self) -> _containers.RepeatedCompositeFieldContainer[_config_pb2.InboundHandlerConfig]: ...
    def __init__(
        self,
        *,
        inbounds: _abc.Iterable[_config_pb2.InboundHandlerConfig] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["inbounds", b"inbounds"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListInboundsResponse: _TypeAlias = ListInboundsResponse  # noqa: Y015

@_typing.final
class GetInboundUserRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    tag: _builtins.str
    email: _builtins.str
    def __init__(
        self,
        *,
        tag: _builtins.str = ...,
        email: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["email", b"email", "tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetInboundUserRequest: _TypeAlias = GetInboundUserRequest  # noqa: Y015

@_typing.final
class GetInboundUserResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def users(self) -> _containers.RepeatedCompositeFieldContainer[_user_pb2.User]: ...
    def __init__(
        self,
        *,
        users: _abc.Iterable[_user_pb2.User] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["users", b"users"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetInboundUserResponse: _TypeAlias = GetInboundUserResponse  # noqa: Y015

@_typing.final
class GetInboundUsersCountResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COUNT_FIELD_NUMBER: _builtins.int
    count: _builtins.int
    def __init__(
        self,
        *,
        count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["count", b"count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetInboundUsersCountResponse: _TypeAlias = GetInboundUsersCountResponse  # noqa: Y015

@_typing.final
class AddOutboundRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OUTBOUND_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def outbound(self) -> _config_pb2.OutboundHandlerConfig: ...
    def __init__(
        self,
        *,
        outbound: _config_pb2.OutboundHandlerConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["outbound", b"outbound"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["outbound", b"outbound"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddOutboundRequest: _TypeAlias = AddOutboundRequest  # noqa: Y015

@_typing.final
class AddOutboundResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddOutboundResponse: _TypeAlias = AddOutboundResponse  # noqa: Y015

@_typing.final
class RemoveOutboundRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    tag: _builtins.str
    def __init__(
        self,
        *,
        tag: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RemoveOutboundRequest: _TypeAlias = RemoveOutboundRequest  # noqa: Y015

@_typing.final
class RemoveOutboundResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RemoveOutboundResponse: _TypeAlias = RemoveOutboundResponse  # noqa: Y015

@_typing.final
class AlterOutboundRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    OPERATION_FIELD_NUMBER: _builtins.int
    tag: _builtins.str
    @_builtins.property
    def operation(self) -> _typed_message_pb2.TypedMessage: ...
    def __init__(
        self,
        *,
        tag: _builtins.str = ...,
        operation: _typed_message_pb2.TypedMessage | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["operation", b"operation"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["operation", b"operation", "tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AlterOutboundRequest: _TypeAlias = AlterOutboundRequest  # noqa: Y015

@_typing.final
class AlterOutboundResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AlterOutboundResponse: _TypeAlias = AlterOutboundResponse  # noqa: Y015

@_typing.final
class ListOutboundsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListOutboundsRequest: _TypeAlias = ListOutboundsRequest  # noqa: Y015

@_typing.final
class ListOutboundsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OUTBOUNDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def outbounds(self) -> _containers.RepeatedCompositeFieldContainer[_config_pb2.OutboundHandlerConfig]: ...
    def __init__(
        self,
        *,
        outbounds: _abc.Iterable[_config_pb2.OutboundHandlerConfig] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["outbounds", b"outbounds"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListOutboundsResponse: _TypeAlias = ListOutboundsResponse  # noqa: Y015

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
