"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from app.proxyman.command import command_pb2 as _command_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class HandlerServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> HandlerServiceAsyncStub: ...
    AddInbound: _grpc.UnaryUnaryMultiCallable[_command_pb2.AddInboundRequest, _command_pb2.AddInboundResponse]
    RemoveInbound: _grpc.UnaryUnaryMultiCallable[_command_pb2.RemoveInboundRequest, _command_pb2.RemoveInboundResponse]
    AlterInbound: _grpc.UnaryUnaryMultiCallable[_command_pb2.AlterInboundRequest, _command_pb2.AlterInboundResponse]
    ListInbounds: _grpc.UnaryUnaryMultiCallable[_command_pb2.ListInboundsRequest, _command_pb2.ListInboundsResponse]
    GetInboundUsers: _grpc.UnaryUnaryMultiCallable[_command_pb2.GetInboundUserRequest, _command_pb2.GetInboundUserResponse]
    GetInboundUsersCount: _grpc.UnaryUnaryMultiCallable[_command_pb2.GetInboundUserRequest, _command_pb2.GetInboundUsersCountResponse]
    AddOutbound: _grpc.UnaryUnaryMultiCallable[_command_pb2.AddOutboundRequest, _command_pb2.AddOutboundResponse]
    RemoveOutbound: _grpc.UnaryUnaryMultiCallable[_command_pb2.RemoveOutboundRequest, _command_pb2.RemoveOutboundResponse]
    AlterOutbound: _grpc.UnaryUnaryMultiCallable[_command_pb2.AlterOutboundRequest, _command_pb2.AlterOutboundResponse]
    ListOutbounds: _grpc.UnaryUnaryMultiCallable[_command_pb2.ListOutboundsRequest, _command_pb2.ListOutboundsResponse]

@_typing.type_check_only
class HandlerServiceAsyncStub(HandlerServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    AddInbound: _aio.UnaryUnaryMultiCallable[_command_pb2.AddInboundRequest, _command_pb2.AddInboundResponse]  # type: ignore[assignment]
    RemoveInbound: _aio.UnaryUnaryMultiCallable[_command_pb2.RemoveInboundRequest, _command_pb2.RemoveInboundResponse]  # type: ignore[assignment]
    AlterInbound: _aio.UnaryUnaryMultiCallable[_command_pb2.AlterInboundRequest, _command_pb2.AlterInboundResponse]  # type: ignore[assignment]
    ListInbounds: _aio.UnaryUnaryMultiCallable[_command_pb2.ListInboundsRequest, _command_pb2.ListInboundsResponse]  # type: ignore[assignment]
    GetInboundUsers: _aio.UnaryUnaryMultiCallable[_command_pb2.GetInboundUserRequest, _command_pb2.GetInboundUserResponse]  # type: ignore[assignment]
    GetInboundUsersCount: _aio.UnaryUnaryMultiCallable[_command_pb2.GetInboundUserRequest, _command_pb2.GetInboundUsersCountResponse]  # type: ignore[assignment]
    AddOutbound: _aio.UnaryUnaryMultiCallable[_command_pb2.AddOutboundRequest, _command_pb2.AddOutboundResponse]  # type: ignore[assignment]
    RemoveOutbound: _aio.UnaryUnaryMultiCallable[_command_pb2.RemoveOutboundRequest, _command_pb2.RemoveOutboundResponse]  # type: ignore[assignment]
    AlterOutbound: _aio.UnaryUnaryMultiCallable[_command_pb2.AlterOutboundRequest, _command_pb2.AlterOutboundResponse]  # type: ignore[assignment]
    ListOutbounds: _aio.UnaryUnaryMultiCallable[_command_pb2.ListOutboundsRequest, _command_pb2.ListOutboundsResponse]  # type: ignore[assignment]

class HandlerServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def AddInbound(
        self,
        request: _command_pb2.AddInboundRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.AddInboundResponse, _abc.Awaitable[_command_pb2.AddInboundResponse]]: ...

    @_abc_1.abstractmethod
    def RemoveInbound(
        self,
        request: _command_pb2.RemoveInboundRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.RemoveInboundResponse, _abc.Awaitable[_command_pb2.RemoveInboundResponse]]: ...

    @_abc_1.abstractmethod
    def AlterInbound(
        self,
        request: _command_pb2.AlterInboundRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.AlterInboundResponse, _abc.Awaitable[_command_pb2.AlterInboundResponse]]: ...

    @_abc_1.abstractmethod
    def ListInbounds(
        self,
        request: _command_pb2.ListInboundsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.ListInboundsResponse, _abc.Awaitable[_command_pb2.ListInboundsResponse]]: ...

    @_abc_1.abstractmethod
    def GetInboundUsers(
        self,
        request: _command_pb2.GetInboundUserRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.GetInboundUserResponse, _abc.Awaitable[_command_pb2.GetInboundUserResponse]]: ...

    @_abc_1.abstractmethod
    def GetInboundUsersCount(
        self,
        request: _command_pb2.GetInboundUserRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.GetInboundUsersCountResponse, _abc.Awaitable[_command_pb2.GetInboundUsersCountResponse]]: ...

    @_abc_1.abstractmethod
    def AddOutbound(
        self,
        request: _command_pb2.AddOutboundRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.AddOutboundResponse, _abc.Awaitable[_command_pb2.AddOutboundResponse]]: ...

    @_abc_1.abstractmethod
    def RemoveOutbound(
        self,
        request: _command_pb2.RemoveOutboundRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.RemoveOutboundResponse, _abc.Awaitable[_command_pb2.RemoveOutboundResponse]]: ...

    @_abc_1.abstractmethod
    def AlterOutbound(
        self,
        request: _command_pb2.AlterOutboundRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.AlterOutboundResponse, _abc.Awaitable[_command_pb2.AlterOutboundResponse]]: ...

    @_abc_1.abstractmethod
    def ListOutbounds(
        self,
        request: _command_pb2.ListOutboundsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.ListOutboundsResponse, _abc.Awaitable[_command_pb2.ListOutboundsResponse]]: ...

def add_HandlerServiceServicer_to_server(servicer: HandlerServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
