"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class FakeDnsPool(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IP_POOL_FIELD_NUMBER: _builtins.int
    LRUSIZE_FIELD_NUMBER: _builtins.int
    ip_pool: _builtins.str
    """CIDR of IP pool used as fake DNS IP"""
    lruSize: _builtins.int
    """Size of Pool for remembering relationship between domain name and IP address"""
    def __init__(
        self,
        *,
        ip_pool: _builtins.str = ...,
        lruSize: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ip_pool", b"ip_pool", "lruSize", b"lruSize"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FakeDnsPool: _TypeAlias = FakeDnsPool  # noqa: Y015

@_typing.final
class FakeDnsPoolMulti(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POOLS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def pools(self) -> _containers.RepeatedCompositeFieldContainer[Global___FakeDnsPool]: ...
    def __init__(
        self,
        *,
        pools: _abc.Iterable[Global___FakeDnsPool] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pools", b"pools"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FakeDnsPoolMulti: _TypeAlias = FakeDnsPoolMulti  # noqa: Y015
