"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from transport.internet import config_pb2 as _config_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class RangeConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FROM_FIELD_NUMBER: _builtins.int
    TO_FIELD_NUMBER: _builtins.int
    to: _builtins.int
    def __init__(
        self,
        *,
        to: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["from", b"from", "to", b"to"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RangeConfig: _TypeAlias = RangeConfig  # noqa: Y015

@_typing.final
class XmuxConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MAXCONCURRENCY_FIELD_NUMBER: _builtins.int
    MAXCONNECTIONS_FIELD_NUMBER: _builtins.int
    CMAXREUSETIMES_FIELD_NUMBER: _builtins.int
    HMAXREQUESTTIMES_FIELD_NUMBER: _builtins.int
    HMAXREUSABLESECS_FIELD_NUMBER: _builtins.int
    HKEEPALIVEPERIOD_FIELD_NUMBER: _builtins.int
    hKeepAlivePeriod: _builtins.int
    @_builtins.property
    def maxConcurrency(self) -> Global___RangeConfig: ...
    @_builtins.property
    def maxConnections(self) -> Global___RangeConfig: ...
    @_builtins.property
    def cMaxReuseTimes(self) -> Global___RangeConfig: ...
    @_builtins.property
    def hMaxRequestTimes(self) -> Global___RangeConfig: ...
    @_builtins.property
    def hMaxReusableSecs(self) -> Global___RangeConfig: ...
    def __init__(
        self,
        *,
        maxConcurrency: Global___RangeConfig | None = ...,
        maxConnections: Global___RangeConfig | None = ...,
        cMaxReuseTimes: Global___RangeConfig | None = ...,
        hMaxRequestTimes: Global___RangeConfig | None = ...,
        hMaxReusableSecs: Global___RangeConfig | None = ...,
        hKeepAlivePeriod: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["cMaxReuseTimes", b"cMaxReuseTimes", "hMaxRequestTimes", b"hMaxRequestTimes", "hMaxReusableSecs", b"hMaxReusableSecs", "maxConcurrency", b"maxConcurrency", "maxConnections", b"maxConnections"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cMaxReuseTimes", b"cMaxReuseTimes", "hKeepAlivePeriod", b"hKeepAlivePeriod", "hMaxRequestTimes", b"hMaxRequestTimes", "hMaxReusableSecs", b"hMaxReusableSecs", "maxConcurrency", b"maxConcurrency", "maxConnections", b"maxConnections"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___XmuxConfig: _TypeAlias = XmuxConfig  # noqa: Y015

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class HeadersEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    HOST_FIELD_NUMBER: _builtins.int
    PATH_FIELD_NUMBER: _builtins.int
    MODE_FIELD_NUMBER: _builtins.int
    HEADERS_FIELD_NUMBER: _builtins.int
    XPADDINGBYTES_FIELD_NUMBER: _builtins.int
    NOGRPCHEADER_FIELD_NUMBER: _builtins.int
    NOSSEHEADER_FIELD_NUMBER: _builtins.int
    SCMAXEACHPOSTBYTES_FIELD_NUMBER: _builtins.int
    SCMINPOSTSINTERVALMS_FIELD_NUMBER: _builtins.int
    SCMAXBUFFEREDPOSTS_FIELD_NUMBER: _builtins.int
    SCSTREAMUPSERVERSECS_FIELD_NUMBER: _builtins.int
    XMUX_FIELD_NUMBER: _builtins.int
    DOWNLOADSETTINGS_FIELD_NUMBER: _builtins.int
    XPADDINGOBFSMODE_FIELD_NUMBER: _builtins.int
    XPADDINGKEY_FIELD_NUMBER: _builtins.int
    XPADDINGHEADER_FIELD_NUMBER: _builtins.int
    XPADDINGPLACEMENT_FIELD_NUMBER: _builtins.int
    XPADDINGMETHOD_FIELD_NUMBER: _builtins.int
    UPLINKHTTPMETHOD_FIELD_NUMBER: _builtins.int
    SESSIONPLACEMENT_FIELD_NUMBER: _builtins.int
    SESSIONKEY_FIELD_NUMBER: _builtins.int
    SEQPLACEMENT_FIELD_NUMBER: _builtins.int
    SEQKEY_FIELD_NUMBER: _builtins.int
    UPLINKDATAPLACEMENT_FIELD_NUMBER: _builtins.int
    UPLINKDATAKEY_FIELD_NUMBER: _builtins.int
    UPLINKCHUNKSIZE_FIELD_NUMBER: _builtins.int
    SERVERMAXHEADERBYTES_FIELD_NUMBER: _builtins.int
    host: _builtins.str
    path: _builtins.str
    mode: _builtins.str
    noGRPCHeader: _builtins.bool
    noSSEHeader: _builtins.bool
    scMaxBufferedPosts: _builtins.int
    xPaddingObfsMode: _builtins.bool
    xPaddingKey: _builtins.str
    xPaddingHeader: _builtins.str
    xPaddingPlacement: _builtins.str
    xPaddingMethod: _builtins.str
    uplinkHTTPMethod: _builtins.str
    sessionPlacement: _builtins.str
    sessionKey: _builtins.str
    seqPlacement: _builtins.str
    seqKey: _builtins.str
    uplinkDataPlacement: _builtins.str
    uplinkDataKey: _builtins.str
    serverMaxHeaderBytes: _builtins.int
    @_builtins.property
    def headers(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def xPaddingBytes(self) -> Global___RangeConfig: ...
    @_builtins.property
    def scMaxEachPostBytes(self) -> Global___RangeConfig: ...
    @_builtins.property
    def scMinPostsIntervalMs(self) -> Global___RangeConfig: ...
    @_builtins.property
    def scStreamUpServerSecs(self) -> Global___RangeConfig: ...
    @_builtins.property
    def xmux(self) -> Global___XmuxConfig: ...
    @_builtins.property
    def downloadSettings(self) -> _config_pb2.StreamConfig: ...
    @_builtins.property
    def uplinkChunkSize(self) -> Global___RangeConfig: ...
    def __init__(
        self,
        *,
        host: _builtins.str = ...,
        path: _builtins.str = ...,
        mode: _builtins.str = ...,
        headers: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        xPaddingBytes: Global___RangeConfig | None = ...,
        noGRPCHeader: _builtins.bool = ...,
        noSSEHeader: _builtins.bool = ...,
        scMaxEachPostBytes: Global___RangeConfig | None = ...,
        scMinPostsIntervalMs: Global___RangeConfig | None = ...,
        scMaxBufferedPosts: _builtins.int = ...,
        scStreamUpServerSecs: Global___RangeConfig | None = ...,
        xmux: Global___XmuxConfig | None = ...,
        downloadSettings: _config_pb2.StreamConfig | None = ...,
        xPaddingObfsMode: _builtins.bool = ...,
        xPaddingKey: _builtins.str = ...,
        xPaddingHeader: _builtins.str = ...,
        xPaddingPlacement: _builtins.str = ...,
        xPaddingMethod: _builtins.str = ...,
        uplinkHTTPMethod: _builtins.str = ...,
        sessionPlacement: _builtins.str = ...,
        sessionKey: _builtins.str = ...,
        seqPlacement: _builtins.str = ...,
        seqKey: _builtins.str = ...,
        uplinkDataPlacement: _builtins.str = ...,
        uplinkDataKey: _builtins.str = ...,
        uplinkChunkSize: Global___RangeConfig | None = ...,
        serverMaxHeaderBytes: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["downloadSettings", b"downloadSettings", "scMaxEachPostBytes", b"scMaxEachPostBytes", "scMinPostsIntervalMs", b"scMinPostsIntervalMs", "scStreamUpServerSecs", b"scStreamUpServerSecs", "uplinkChunkSize", b"uplinkChunkSize", "xPaddingBytes", b"xPaddingBytes", "xmux", b"xmux"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["downloadSettings", b"downloadSettings", "headers", b"headers", "host", b"host", "mode", b"mode", "noGRPCHeader", b"noGRPCHeader", "noSSEHeader", b"noSSEHeader", "path", b"path", "scMaxBufferedPosts", b"scMaxBufferedPosts", "scMaxEachPostBytes", b"scMaxEachPostBytes", "scMinPostsIntervalMs", b"scMinPostsIntervalMs", "scStreamUpServerSecs", b"scStreamUpServerSecs", "seqKey", b"seqKey", "seqPlacement", b"seqPlacement", "serverMaxHeaderBytes", b"serverMaxHeaderBytes", "sessionKey", b"sessionKey", "sessionPlacement", b"sessionPlacement", "uplinkChunkSize", b"uplinkChunkSize", "uplinkDataKey", b"uplinkDataKey", "uplinkDataPlacement", b"uplinkDataPlacement", "uplinkHTTPMethod", b"uplinkHTTPMethod", "xPaddingBytes", b"xPaddingBytes", "xPaddingHeader", b"xPaddingHeader", "xPaddingKey", b"xPaddingKey", "xPaddingMethod", b"xPaddingMethod", "xPaddingObfsMode", b"xPaddingObfsMode", "xPaddingPlacement", b"xPaddingPlacement", "xmux", b"xmux"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
