"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class HeaderEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    HOST_FIELD_NUMBER: _builtins.int
    PATH_FIELD_NUMBER: _builtins.int
    HEADER_FIELD_NUMBER: _builtins.int
    ACCEPT_PROXY_PROTOCOL_FIELD_NUMBER: _builtins.int
    ED_FIELD_NUMBER: _builtins.int
    HEARTBEATPERIOD_FIELD_NUMBER: _builtins.int
    host: _builtins.str
    path: _builtins.str
    """URL path to the WebSocket service. Empty value means root(/)."""
    accept_proxy_protocol: _builtins.bool
    ed: _builtins.int
    heartbeatPeriod: _builtins.int
    @_builtins.property
    def header(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        host: _builtins.str = ...,
        path: _builtins.str = ...,
        header: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        accept_proxy_protocol: _builtins.bool = ...,
        ed: _builtins.int = ...,
        heartbeatPeriod: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accept_proxy_protocol", b"accept_proxy_protocol", "ed", b"ed", "header", b"header", "heartbeatPeriod", b"heartbeatPeriod", "host", b"host", "path", b"path"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
