"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from common.protocol import user_pb2 as _user_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Fallback(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    ALPN_FIELD_NUMBER: _builtins.int
    PATH_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    DEST_FIELD_NUMBER: _builtins.int
    XVER_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    alpn: _builtins.str
    path: _builtins.str
    type: _builtins.str
    dest: _builtins.str
    xver: _builtins.int
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        alpn: _builtins.str = ...,
        path: _builtins.str = ...,
        type: _builtins.str = ...,
        dest: _builtins.str = ...,
        xver: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["alpn", b"alpn", "dest", b"dest", "name", b"name", "path", b"path", "type", b"type", "xver", b"xver"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Fallback: _TypeAlias = Fallback  # noqa: Y015

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLIENTS_FIELD_NUMBER: _builtins.int
    FALLBACKS_FIELD_NUMBER: _builtins.int
    DECRYPTION_FIELD_NUMBER: _builtins.int
    XORMODE_FIELD_NUMBER: _builtins.int
    SECONDS_FROM_FIELD_NUMBER: _builtins.int
    SECONDS_TO_FIELD_NUMBER: _builtins.int
    PADDING_FIELD_NUMBER: _builtins.int
    decryption: _builtins.str
    xorMode: _builtins.int
    seconds_from: _builtins.int
    seconds_to: _builtins.int
    padding: _builtins.str
    @_builtins.property
    def clients(self) -> _containers.RepeatedCompositeFieldContainer[_user_pb2.User]: ...
    @_builtins.property
    def fallbacks(self) -> _containers.RepeatedCompositeFieldContainer[Global___Fallback]: ...
    def __init__(
        self,
        *,
        clients: _abc.Iterable[_user_pb2.User] | None = ...,
        fallbacks: _abc.Iterable[Global___Fallback] | None = ...,
        decryption: _builtins.str = ...,
        xorMode: _builtins.int = ...,
        seconds_from: _builtins.int = ...,
        seconds_to: _builtins.int = ...,
        padding: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["clients", b"clients", "decryption", b"decryption", "fallbacks", b"fallbacks", "padding", b"padding", "seconds_from", b"seconds_from", "seconds_to", b"seconds_to", "xorMode", b"xorMode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
