"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from common.net import address_pb2 as _address_pb2
from common.net import network_pb2 as _network_pb2
from common.protocol import user_pb2 as _user_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ServerConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    METHOD_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    LEVEL_FIELD_NUMBER: _builtins.int
    NETWORK_FIELD_NUMBER: _builtins.int
    method: _builtins.str
    key: _builtins.str
    email: _builtins.str
    level: _builtins.int
    @_builtins.property
    def network(self) -> _containers.RepeatedScalarFieldContainer[_network_pb2.Network.ValueType]: ...
    def __init__(
        self,
        *,
        method: _builtins.str = ...,
        key: _builtins.str = ...,
        email: _builtins.str = ...,
        level: _builtins.int = ...,
        network: _abc.Iterable[_network_pb2.Network.ValueType] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["email", b"email", "key", b"key", "level", b"level", "method", b"method", "network", b"network"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ServerConfig: _TypeAlias = ServerConfig  # noqa: Y015

@_typing.final
class MultiUserServerConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    METHOD_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    USERS_FIELD_NUMBER: _builtins.int
    NETWORK_FIELD_NUMBER: _builtins.int
    method: _builtins.str
    key: _builtins.str
    @_builtins.property
    def users(self) -> _containers.RepeatedCompositeFieldContainer[_user_pb2.User]: ...
    @_builtins.property
    def network(self) -> _containers.RepeatedScalarFieldContainer[_network_pb2.Network.ValueType]: ...
    def __init__(
        self,
        *,
        method: _builtins.str = ...,
        key: _builtins.str = ...,
        users: _abc.Iterable[_user_pb2.User] | None = ...,
        network: _abc.Iterable[_network_pb2.Network.ValueType] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "method", b"method", "network", b"network", "users", b"users"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MultiUserServerConfig: _TypeAlias = MultiUserServerConfig  # noqa: Y015

@_typing.final
class RelayDestination(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    ADDRESS_FIELD_NUMBER: _builtins.int
    PORT_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    LEVEL_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    port: _builtins.int
    email: _builtins.str
    level: _builtins.int
    @_builtins.property
    def address(self) -> _address_pb2.IPOrDomain: ...
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        address: _address_pb2.IPOrDomain | None = ...,
        port: _builtins.int = ...,
        email: _builtins.str = ...,
        level: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["address", b"address"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "email", b"email", "key", b"key", "level", b"level", "port", b"port"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RelayDestination: _TypeAlias = RelayDestination  # noqa: Y015

@_typing.final
class RelayServerConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    METHOD_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    DESTINATIONS_FIELD_NUMBER: _builtins.int
    NETWORK_FIELD_NUMBER: _builtins.int
    method: _builtins.str
    key: _builtins.str
    @_builtins.property
    def destinations(self) -> _containers.RepeatedCompositeFieldContainer[Global___RelayDestination]: ...
    @_builtins.property
    def network(self) -> _containers.RepeatedScalarFieldContainer[_network_pb2.Network.ValueType]: ...
    def __init__(
        self,
        *,
        method: _builtins.str = ...,
        key: _builtins.str = ...,
        destinations: _abc.Iterable[Global___RelayDestination] | None = ...,
        network: _abc.Iterable[_network_pb2.Network.ValueType] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["destinations", b"destinations", "key", b"key", "method", b"method", "network", b"network"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RelayServerConfig: _TypeAlias = RelayServerConfig  # noqa: Y015

@_typing.final
class Account(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Account: _TypeAlias = Account  # noqa: Y015

@_typing.final
class ClientConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: _builtins.int
    PORT_FIELD_NUMBER: _builtins.int
    METHOD_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    UDP_OVER_TCP_FIELD_NUMBER: _builtins.int
    UDP_OVER_TCP_VERSION_FIELD_NUMBER: _builtins.int
    port: _builtins.int
    method: _builtins.str
    key: _builtins.str
    udp_over_tcp: _builtins.bool
    udp_over_tcp_version: _builtins.int
    @_builtins.property
    def address(self) -> _address_pb2.IPOrDomain: ...
    def __init__(
        self,
        *,
        address: _address_pb2.IPOrDomain | None = ...,
        port: _builtins.int = ...,
        method: _builtins.str = ...,
        key: _builtins.str = ...,
        udp_over_tcp: _builtins.bool = ...,
        udp_over_tcp_version: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["address", b"address"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "key", b"key", "method", b"method", "port", b"port", "udp_over_tcp", b"udp_over_tcp", "udp_over_tcp_version", b"udp_over_tcp_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ClientConfig: _TypeAlias = ClientConfig  # noqa: Y015
