"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from common.protocol import server_spec_pb2 as _server_spec_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from transport.internet import config_pb2 as _config_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DestinationOverride(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SERVER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def server(self) -> _server_spec_pb2.ServerEndpoint: ...
    def __init__(
        self,
        *,
        server: _server_spec_pb2.ServerEndpoint | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["server", b"server"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["server", b"server"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DestinationOverride: _TypeAlias = DestinationOverride  # noqa: Y015

@_typing.final
class Fragment(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PACKETS_FROM_FIELD_NUMBER: _builtins.int
    PACKETS_TO_FIELD_NUMBER: _builtins.int
    LENGTH_MIN_FIELD_NUMBER: _builtins.int
    LENGTH_MAX_FIELD_NUMBER: _builtins.int
    INTERVAL_MIN_FIELD_NUMBER: _builtins.int
    INTERVAL_MAX_FIELD_NUMBER: _builtins.int
    MAX_SPLIT_MIN_FIELD_NUMBER: _builtins.int
    MAX_SPLIT_MAX_FIELD_NUMBER: _builtins.int
    packets_from: _builtins.int
    packets_to: _builtins.int
    length_min: _builtins.int
    length_max: _builtins.int
    interval_min: _builtins.int
    interval_max: _builtins.int
    max_split_min: _builtins.int
    max_split_max: _builtins.int
    def __init__(
        self,
        *,
        packets_from: _builtins.int = ...,
        packets_to: _builtins.int = ...,
        length_min: _builtins.int = ...,
        length_max: _builtins.int = ...,
        interval_min: _builtins.int = ...,
        interval_max: _builtins.int = ...,
        max_split_min: _builtins.int = ...,
        max_split_max: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["interval_max", b"interval_max", "interval_min", b"interval_min", "length_max", b"length_max", "length_min", b"length_min", "max_split_max", b"max_split_max", "max_split_min", b"max_split_min", "packets_from", b"packets_from", "packets_to", b"packets_to"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Fragment: _TypeAlias = Fragment  # noqa: Y015

@_typing.final
class Noise(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LENGTH_MIN_FIELD_NUMBER: _builtins.int
    LENGTH_MAX_FIELD_NUMBER: _builtins.int
    DELAY_MIN_FIELD_NUMBER: _builtins.int
    DELAY_MAX_FIELD_NUMBER: _builtins.int
    PACKET_FIELD_NUMBER: _builtins.int
    APPLY_TO_FIELD_NUMBER: _builtins.int
    length_min: _builtins.int
    length_max: _builtins.int
    delay_min: _builtins.int
    delay_max: _builtins.int
    packet: _builtins.bytes
    apply_to: _builtins.str
    def __init__(
        self,
        *,
        length_min: _builtins.int = ...,
        length_max: _builtins.int = ...,
        delay_min: _builtins.int = ...,
        delay_max: _builtins.int = ...,
        packet: _builtins.bytes = ...,
        apply_to: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["apply_to", b"apply_to", "delay_max", b"delay_max", "delay_min", b"delay_min", "length_max", b"length_max", "length_min", b"length_min", "packet", b"packet"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Noise: _TypeAlias = Noise  # noqa: Y015

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DOMAIN_STRATEGY_FIELD_NUMBER: _builtins.int
    DESTINATION_OVERRIDE_FIELD_NUMBER: _builtins.int
    USER_LEVEL_FIELD_NUMBER: _builtins.int
    FRAGMENT_FIELD_NUMBER: _builtins.int
    PROXY_PROTOCOL_FIELD_NUMBER: _builtins.int
    NOISES_FIELD_NUMBER: _builtins.int
    domain_strategy: _config_pb2.DomainStrategy.ValueType
    user_level: _builtins.int
    proxy_protocol: _builtins.int
    @_builtins.property
    def destination_override(self) -> Global___DestinationOverride: ...
    @_builtins.property
    def fragment(self) -> Global___Fragment: ...
    @_builtins.property
    def noises(self) -> _containers.RepeatedCompositeFieldContainer[Global___Noise]: ...
    def __init__(
        self,
        *,
        domain_strategy: _config_pb2.DomainStrategy.ValueType = ...,
        destination_override: Global___DestinationOverride | None = ...,
        user_level: _builtins.int = ...,
        fragment: Global___Fragment | None = ...,
        proxy_protocol: _builtins.int = ...,
        noises: _abc.Iterable[Global___Noise] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["destination_override", b"destination_override", "fragment", b"fragment"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["destination_override", b"destination_override", "domain_strategy", b"domain_strategy", "fragment", b"fragment", "noises", b"noises", "proxy_protocol", b"proxy_protocol", "user_level", b"user_level"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
