"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from app.router.command import command_pb2 as _command_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class RoutingServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> RoutingServiceAsyncStub: ...
    SubscribeRoutingStats: _grpc.UnaryStreamMultiCallable[_command_pb2.SubscribeRoutingStatsRequest, _command_pb2.RoutingContext]
    TestRoute: _grpc.UnaryUnaryMultiCallable[_command_pb2.TestRouteRequest, _command_pb2.RoutingContext]
    GetBalancerInfo: _grpc.UnaryUnaryMultiCallable[_command_pb2.GetBalancerInfoRequest, _command_pb2.GetBalancerInfoResponse]
    OverrideBalancerTarget: _grpc.UnaryUnaryMultiCallable[_command_pb2.OverrideBalancerTargetRequest, _command_pb2.OverrideBalancerTargetResponse]
    AddRule: _grpc.UnaryUnaryMultiCallable[_command_pb2.AddRuleRequest, _command_pb2.AddRuleResponse]
    RemoveRule: _grpc.UnaryUnaryMultiCallable[_command_pb2.RemoveRuleRequest, _command_pb2.RemoveRuleResponse]
    ListRule: _grpc.UnaryUnaryMultiCallable[_command_pb2.ListRuleRequest, _command_pb2.ListRuleResponse]

@_typing.type_check_only
class RoutingServiceAsyncStub(RoutingServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    SubscribeRoutingStats: _aio.UnaryStreamMultiCallable[_command_pb2.SubscribeRoutingStatsRequest, _command_pb2.RoutingContext]  # type: ignore[assignment]
    TestRoute: _aio.UnaryUnaryMultiCallable[_command_pb2.TestRouteRequest, _command_pb2.RoutingContext]  # type: ignore[assignment]
    GetBalancerInfo: _aio.UnaryUnaryMultiCallable[_command_pb2.GetBalancerInfoRequest, _command_pb2.GetBalancerInfoResponse]  # type: ignore[assignment]
    OverrideBalancerTarget: _aio.UnaryUnaryMultiCallable[_command_pb2.OverrideBalancerTargetRequest, _command_pb2.OverrideBalancerTargetResponse]  # type: ignore[assignment]
    AddRule: _aio.UnaryUnaryMultiCallable[_command_pb2.AddRuleRequest, _command_pb2.AddRuleResponse]  # type: ignore[assignment]
    RemoveRule: _aio.UnaryUnaryMultiCallable[_command_pb2.RemoveRuleRequest, _command_pb2.RemoveRuleResponse]  # type: ignore[assignment]
    ListRule: _aio.UnaryUnaryMultiCallable[_command_pb2.ListRuleRequest, _command_pb2.ListRuleResponse]  # type: ignore[assignment]

class RoutingServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def SubscribeRoutingStats(
        self,
        request: _command_pb2.SubscribeRoutingStatsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_command_pb2.RoutingContext], _abc.AsyncIterator[_command_pb2.RoutingContext]]: ...

    @_abc_1.abstractmethod
    def TestRoute(
        self,
        request: _command_pb2.TestRouteRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.RoutingContext, _abc.Awaitable[_command_pb2.RoutingContext]]: ...

    @_abc_1.abstractmethod
    def GetBalancerInfo(
        self,
        request: _command_pb2.GetBalancerInfoRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.GetBalancerInfoResponse, _abc.Awaitable[_command_pb2.GetBalancerInfoResponse]]: ...

    @_abc_1.abstractmethod
    def OverrideBalancerTarget(
        self,
        request: _command_pb2.OverrideBalancerTargetRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.OverrideBalancerTargetResponse, _abc.Awaitable[_command_pb2.OverrideBalancerTargetResponse]]: ...

    @_abc_1.abstractmethod
    def AddRule(
        self,
        request: _command_pb2.AddRuleRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.AddRuleResponse, _abc.Awaitable[_command_pb2.AddRuleResponse]]: ...

    @_abc_1.abstractmethod
    def RemoveRule(
        self,
        request: _command_pb2.RemoveRuleRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.RemoveRuleResponse, _abc.Awaitable[_command_pb2.RemoveRuleResponse]]: ...

    @_abc_1.abstractmethod
    def ListRule(
        self,
        request: _command_pb2.ListRuleRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_command_pb2.ListRuleResponse, _abc.Awaitable[_command_pb2.ListRuleResponse]]: ...

def add_RoutingServiceServicer_to_server(servicer: RoutingServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
