"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from common.net import network_pb2 as _network_pb2
from common.serial import typed_message_pb2 as _typed_message_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class RoutingContext(_message.Message):
    """RoutingContext is the context with information relative to routing process.
    It conforms to the structure of xray.features.routing.Context and
    xray.features.routing.Route.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class AttributesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    INBOUNDTAG_FIELD_NUMBER: _builtins.int
    NETWORK_FIELD_NUMBER: _builtins.int
    SOURCEIPS_FIELD_NUMBER: _builtins.int
    TARGETIPS_FIELD_NUMBER: _builtins.int
    SOURCEPORT_FIELD_NUMBER: _builtins.int
    TARGETPORT_FIELD_NUMBER: _builtins.int
    TARGETDOMAIN_FIELD_NUMBER: _builtins.int
    PROTOCOL_FIELD_NUMBER: _builtins.int
    USER_FIELD_NUMBER: _builtins.int
    ATTRIBUTES_FIELD_NUMBER: _builtins.int
    OUTBOUNDGROUPTAGS_FIELD_NUMBER: _builtins.int
    OUTBOUNDTAG_FIELD_NUMBER: _builtins.int
    LOCALIPS_FIELD_NUMBER: _builtins.int
    LOCALPORT_FIELD_NUMBER: _builtins.int
    VLESSROUTE_FIELD_NUMBER: _builtins.int
    InboundTag: _builtins.str
    Network: _network_pb2.Network.ValueType
    SourcePort: _builtins.int
    TargetPort: _builtins.int
    TargetDomain: _builtins.str
    Protocol: _builtins.str
    User: _builtins.str
    OutboundTag: _builtins.str
    LocalPort: _builtins.int
    VlessRoute: _builtins.int
    @_builtins.property
    def SourceIPs(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
    @_builtins.property
    def TargetIPs(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
    @_builtins.property
    def Attributes(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def OutboundGroupTags(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def LocalIPs(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
    def __init__(
        self,
        *,
        InboundTag: _builtins.str = ...,
        Network: _network_pb2.Network.ValueType = ...,
        SourceIPs: _abc.Iterable[_builtins.bytes] | None = ...,
        TargetIPs: _abc.Iterable[_builtins.bytes] | None = ...,
        SourcePort: _builtins.int = ...,
        TargetPort: _builtins.int = ...,
        TargetDomain: _builtins.str = ...,
        Protocol: _builtins.str = ...,
        User: _builtins.str = ...,
        Attributes: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        OutboundGroupTags: _abc.Iterable[_builtins.str] | None = ...,
        OutboundTag: _builtins.str = ...,
        LocalIPs: _abc.Iterable[_builtins.bytes] | None = ...,
        LocalPort: _builtins.int = ...,
        VlessRoute: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["Attributes", b"Attributes", "InboundTag", b"InboundTag", "LocalIPs", b"LocalIPs", "LocalPort", b"LocalPort", "Network", b"Network", "OutboundGroupTags", b"OutboundGroupTags", "OutboundTag", b"OutboundTag", "Protocol", b"Protocol", "SourceIPs", b"SourceIPs", "SourcePort", b"SourcePort", "TargetDomain", b"TargetDomain", "TargetIPs", b"TargetIPs", "TargetPort", b"TargetPort", "User", b"User", "VlessRoute", b"VlessRoute"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RoutingContext: _TypeAlias = RoutingContext  # noqa: Y015

@_typing.final
class SubscribeRoutingStatsRequest(_message.Message):
    """SubscribeRoutingStatsRequest subscribes to routing statistics channel if
    opened by xray-core.
    * FieldSelectors selects a subset of fields in routing statistics to return.
    Valid selectors:
     - inbound: Selects connection's inbound tag.
     - network: Selects connection's network.
     - ip: Equivalent as "ip_source" and "ip_target", selects both source and
     target IP.
     - port: Equivalent as "port_source" and "port_target", selects both source
     and target port.
     - domain: Selects target domain.
     - protocol: Select connection's protocol.
     - user: Select connection's inbound user email.
     - attributes: Select connection's additional attributes.
     - outbound: Equivalent as "outbound" and "outbound_group", select both
     outbound tag and outbound group tags.
    * If FieldSelectors is left empty, all fields will be returned.
    """

    DESCRIPTOR: _descriptor.Descriptor

    FIELDSELECTORS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def FieldSelectors(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        FieldSelectors: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["FieldSelectors", b"FieldSelectors"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SubscribeRoutingStatsRequest: _TypeAlias = SubscribeRoutingStatsRequest  # noqa: Y015

@_typing.final
class TestRouteRequest(_message.Message):
    """TestRouteRequest manually tests a routing result according to the routing
    context message.
    * RoutingContext is the routing message without outbound information.
    * FieldSelectors selects the fields to return in the routing result. All
    fields are returned if left empty.
    * PublishResult broadcasts the routing result to routing statistics channel
    if set true.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ROUTINGCONTEXT_FIELD_NUMBER: _builtins.int
    FIELDSELECTORS_FIELD_NUMBER: _builtins.int
    PUBLISHRESULT_FIELD_NUMBER: _builtins.int
    PublishResult: _builtins.bool
    @_builtins.property
    def RoutingContext(self) -> Global___RoutingContext: ...
    @_builtins.property
    def FieldSelectors(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        RoutingContext: Global___RoutingContext | None = ...,
        FieldSelectors: _abc.Iterable[_builtins.str] | None = ...,
        PublishResult: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["RoutingContext", b"RoutingContext"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["FieldSelectors", b"FieldSelectors", "PublishResult", b"PublishResult", "RoutingContext", b"RoutingContext"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TestRouteRequest: _TypeAlias = TestRouteRequest  # noqa: Y015

@_typing.final
class PrincipleTargetInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def tag(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        tag: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PrincipleTargetInfo: _TypeAlias = PrincipleTargetInfo  # noqa: Y015

@_typing.final
class OverrideInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TARGET_FIELD_NUMBER: _builtins.int
    target: _builtins.str
    def __init__(
        self,
        *,
        target: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["target", b"target"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___OverrideInfo: _TypeAlias = OverrideInfo  # noqa: Y015

@_typing.final
class BalancerMsg(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OVERRIDE_FIELD_NUMBER: _builtins.int
    PRINCIPLE_TARGET_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def override(self) -> Global___OverrideInfo: ...
    @_builtins.property
    def principle_target(self) -> Global___PrincipleTargetInfo: ...
    def __init__(
        self,
        *,
        override: Global___OverrideInfo | None = ...,
        principle_target: Global___PrincipleTargetInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["override", b"override", "principle_target", b"principle_target"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["override", b"override", "principle_target", b"principle_target"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BalancerMsg: _TypeAlias = BalancerMsg  # noqa: Y015

@_typing.final
class GetBalancerInfoRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    tag: _builtins.str
    def __init__(
        self,
        *,
        tag: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetBalancerInfoRequest: _TypeAlias = GetBalancerInfoRequest  # noqa: Y015

@_typing.final
class GetBalancerInfoResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BALANCER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def balancer(self) -> Global___BalancerMsg: ...
    def __init__(
        self,
        *,
        balancer: Global___BalancerMsg | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["balancer", b"balancer"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["balancer", b"balancer"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetBalancerInfoResponse: _TypeAlias = GetBalancerInfoResponse  # noqa: Y015

@_typing.final
class OverrideBalancerTargetRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BALANCERTAG_FIELD_NUMBER: _builtins.int
    TARGET_FIELD_NUMBER: _builtins.int
    balancerTag: _builtins.str
    target: _builtins.str
    def __init__(
        self,
        *,
        balancerTag: _builtins.str = ...,
        target: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["balancerTag", b"balancerTag", "target", b"target"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___OverrideBalancerTargetRequest: _TypeAlias = OverrideBalancerTargetRequest  # noqa: Y015

@_typing.final
class OverrideBalancerTargetResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___OverrideBalancerTargetResponse: _TypeAlias = OverrideBalancerTargetResponse  # noqa: Y015

@_typing.final
class AddRuleRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIG_FIELD_NUMBER: _builtins.int
    SHOULDAPPEND_FIELD_NUMBER: _builtins.int
    shouldAppend: _builtins.bool
    @_builtins.property
    def config(self) -> _typed_message_pb2.TypedMessage: ...
    def __init__(
        self,
        *,
        config: _typed_message_pb2.TypedMessage | None = ...,
        shouldAppend: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config", "shouldAppend", b"shouldAppend"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddRuleRequest: _TypeAlias = AddRuleRequest  # noqa: Y015

@_typing.final
class AddRuleResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddRuleResponse: _TypeAlias = AddRuleResponse  # noqa: Y015

@_typing.final
class RemoveRuleRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RULETAG_FIELD_NUMBER: _builtins.int
    ruleTag: _builtins.str
    def __init__(
        self,
        *,
        ruleTag: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ruleTag", b"ruleTag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RemoveRuleRequest: _TypeAlias = RemoveRuleRequest  # noqa: Y015

@_typing.final
class RemoveRuleResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RemoveRuleResponse: _TypeAlias = RemoveRuleResponse  # noqa: Y015

@_typing.final
class ListRuleRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListRuleRequest: _TypeAlias = ListRuleRequest  # noqa: Y015

@_typing.final
class ListRuleItem(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    RULETAG_FIELD_NUMBER: _builtins.int
    tag: _builtins.str
    ruleTag: _builtins.str
    def __init__(
        self,
        *,
        tag: _builtins.str = ...,
        ruleTag: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ruleTag", b"ruleTag", "tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListRuleItem: _TypeAlias = ListRuleItem  # noqa: Y015

@_typing.final
class ListRuleResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RULES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def rules(self) -> _containers.RepeatedCompositeFieldContainer[Global___ListRuleItem]: ...
    def __init__(
        self,
        *,
        rules: _abc.Iterable[Global___ListRuleItem] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["rules", b"rules"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListRuleResponse: _TypeAlias = ListRuleResponse  # noqa: Y015

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
