"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from common.net import network_pb2 as _network_pb2
from common.protocol import server_spec_pb2 as _server_spec_pb2
from common.protocol import user_pb2 as _user_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _CipherType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _CipherTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_CipherType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    UNKNOWN: _CipherType.ValueType  # 0
    AES_128_GCM: _CipherType.ValueType  # 5
    AES_256_GCM: _CipherType.ValueType  # 6
    CHACHA20_POLY1305: _CipherType.ValueType  # 7
    XCHACHA20_POLY1305: _CipherType.ValueType  # 8
    NONE: _CipherType.ValueType  # 9

class CipherType(_CipherType, metaclass=_CipherTypeEnumTypeWrapper): ...

UNKNOWN: CipherType.ValueType  # 0
AES_128_GCM: CipherType.ValueType  # 5
AES_256_GCM: CipherType.ValueType  # 6
CHACHA20_POLY1305: CipherType.ValueType  # 7
XCHACHA20_POLY1305: CipherType.ValueType  # 8
NONE: CipherType.ValueType  # 9
Global___CipherType: _TypeAlias = CipherType  # noqa: Y015

@_typing.final
class Account(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PASSWORD_FIELD_NUMBER: _builtins.int
    CIPHER_TYPE_FIELD_NUMBER: _builtins.int
    IV_CHECK_FIELD_NUMBER: _builtins.int
    password: _builtins.str
    cipher_type: Global___CipherType.ValueType
    iv_check: _builtins.bool
    def __init__(
        self,
        *,
        password: _builtins.str = ...,
        cipher_type: Global___CipherType.ValueType = ...,
        iv_check: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cipher_type", b"cipher_type", "iv_check", b"iv_check", "password", b"password"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Account: _TypeAlias = Account  # noqa: Y015

@_typing.final
class ServerConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERS_FIELD_NUMBER: _builtins.int
    NETWORK_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def users(self) -> _containers.RepeatedCompositeFieldContainer[_user_pb2.User]: ...
    @_builtins.property
    def network(self) -> _containers.RepeatedScalarFieldContainer[_network_pb2.Network.ValueType]: ...
    def __init__(
        self,
        *,
        users: _abc.Iterable[_user_pb2.User] | None = ...,
        network: _abc.Iterable[_network_pb2.Network.ValueType] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["network", b"network", "users", b"users"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ServerConfig: _TypeAlias = ServerConfig  # noqa: Y015

@_typing.final
class ClientConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SERVER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def server(self) -> _server_spec_pb2.ServerEndpoint: ...
    def __init__(
        self,
        *,
        server: _server_spec_pb2.ServerEndpoint | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["server", b"server"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["server", b"server"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ClientConfig: _TypeAlias = ClientConfig  # noqa: Y015
