"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: _builtins.int
    SERVICE_NAME_FIELD_NUMBER: _builtins.int
    MULTI_MODE_FIELD_NUMBER: _builtins.int
    IDLE_TIMEOUT_FIELD_NUMBER: _builtins.int
    HEALTH_CHECK_TIMEOUT_FIELD_NUMBER: _builtins.int
    PERMIT_WITHOUT_STREAM_FIELD_NUMBER: _builtins.int
    INITIAL_WINDOWS_SIZE_FIELD_NUMBER: _builtins.int
    USER_AGENT_FIELD_NUMBER: _builtins.int
    authority: _builtins.str
    service_name: _builtins.str
    multi_mode: _builtins.bool
    idle_timeout: _builtins.int
    health_check_timeout: _builtins.int
    permit_without_stream: _builtins.bool
    initial_windows_size: _builtins.int
    user_agent: _builtins.str
    def __init__(
        self,
        *,
        authority: _builtins.str = ...,
        service_name: _builtins.str = ...,
        multi_mode: _builtins.bool = ...,
        idle_timeout: _builtins.int = ...,
        health_check_timeout: _builtins.int = ...,
        permit_without_stream: _builtins.bool = ...,
        initial_windows_size: _builtins.int = ...,
        user_agent: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["authority", b"authority", "health_check_timeout", b"health_check_timeout", "idle_timeout", b"idle_timeout", "initial_windows_size", b"initial_windows_size", "multi_mode", b"multi_mode", "permit_without_stream", b"permit_without_stream", "service_name", b"service_name", "user_agent", b"user_agent"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
