"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from app.router import config_pb2 as _config_pb2
from collections import abc as _abc
from common.net import destination_pb2 as _destination_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _DomainMatchingType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _DomainMatchingTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_DomainMatchingType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    Full: _DomainMatchingType.ValueType  # 0
    Subdomain: _DomainMatchingType.ValueType  # 1
    Keyword: _DomainMatchingType.ValueType  # 2
    Regex: _DomainMatchingType.ValueType  # 3

class DomainMatchingType(_DomainMatchingType, metaclass=_DomainMatchingTypeEnumTypeWrapper): ...

Full: DomainMatchingType.ValueType  # 0
Subdomain: DomainMatchingType.ValueType  # 1
Keyword: DomainMatchingType.ValueType  # 2
Regex: DomainMatchingType.ValueType  # 3
Global___DomainMatchingType: _TypeAlias = DomainMatchingType  # noqa: Y015

class _QueryStrategy:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _QueryStrategyEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_QueryStrategy.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    USE_IP: _QueryStrategy.ValueType  # 0
    USE_IP4: _QueryStrategy.ValueType  # 1
    USE_IP6: _QueryStrategy.ValueType  # 2
    USE_SYS: _QueryStrategy.ValueType  # 3

class QueryStrategy(_QueryStrategy, metaclass=_QueryStrategyEnumTypeWrapper): ...

USE_IP: QueryStrategy.ValueType  # 0
USE_IP4: QueryStrategy.ValueType  # 1
USE_IP6: QueryStrategy.ValueType  # 2
USE_SYS: QueryStrategy.ValueType  # 3
Global___QueryStrategy: _TypeAlias = QueryStrategy  # noqa: Y015

@_typing.final
class NameServer(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class PriorityDomain(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TYPE_FIELD_NUMBER: _builtins.int
        DOMAIN_FIELD_NUMBER: _builtins.int
        type: Global___DomainMatchingType.ValueType
        domain: _builtins.str
        def __init__(
            self,
            *,
            type: Global___DomainMatchingType.ValueType = ...,
            domain: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["domain", b"domain", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class OriginalRule(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        RULE_FIELD_NUMBER: _builtins.int
        SIZE_FIELD_NUMBER: _builtins.int
        rule: _builtins.str
        size: _builtins.int
        def __init__(
            self,
            *,
            rule: _builtins.str = ...,
            size: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["rule", b"rule", "size", b"size"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    ADDRESS_FIELD_NUMBER: _builtins.int
    CLIENT_IP_FIELD_NUMBER: _builtins.int
    SKIPFALLBACK_FIELD_NUMBER: _builtins.int
    PRIORITIZED_DOMAIN_FIELD_NUMBER: _builtins.int
    EXPECTED_GEOIP_FIELD_NUMBER: _builtins.int
    ORIGINAL_RULES_FIELD_NUMBER: _builtins.int
    QUERY_STRATEGY_FIELD_NUMBER: _builtins.int
    ACTPRIOR_FIELD_NUMBER: _builtins.int
    TAG_FIELD_NUMBER: _builtins.int
    TIMEOUTMS_FIELD_NUMBER: _builtins.int
    DISABLECACHE_FIELD_NUMBER: _builtins.int
    SERVESTALE_FIELD_NUMBER: _builtins.int
    SERVEEXPIREDTTL_FIELD_NUMBER: _builtins.int
    FINALQUERY_FIELD_NUMBER: _builtins.int
    UNEXPECTED_GEOIP_FIELD_NUMBER: _builtins.int
    ACTUNPRIOR_FIELD_NUMBER: _builtins.int
    POLICYID_FIELD_NUMBER: _builtins.int
    client_ip: _builtins.bytes
    skipFallback: _builtins.bool
    query_strategy: Global___QueryStrategy.ValueType
    actPrior: _builtins.bool
    tag: _builtins.str
    timeoutMs: _builtins.int
    disableCache: _builtins.bool
    serveStale: _builtins.bool
    serveExpiredTTL: _builtins.int
    finalQuery: _builtins.bool
    actUnprior: _builtins.bool
    policyID: _builtins.int
    @_builtins.property
    def address(self) -> _destination_pb2.Endpoint: ...
    @_builtins.property
    def prioritized_domain(self) -> _containers.RepeatedCompositeFieldContainer[Global___NameServer.PriorityDomain]: ...
    @_builtins.property
    def expected_geoip(self) -> _containers.RepeatedCompositeFieldContainer[_config_pb2.GeoIP]: ...
    @_builtins.property
    def original_rules(self) -> _containers.RepeatedCompositeFieldContainer[Global___NameServer.OriginalRule]: ...
    @_builtins.property
    def unexpected_geoip(self) -> _containers.RepeatedCompositeFieldContainer[_config_pb2.GeoIP]: ...
    def __init__(
        self,
        *,
        address: _destination_pb2.Endpoint | None = ...,
        client_ip: _builtins.bytes = ...,
        skipFallback: _builtins.bool = ...,
        prioritized_domain: _abc.Iterable[Global___NameServer.PriorityDomain] | None = ...,
        expected_geoip: _abc.Iterable[_config_pb2.GeoIP] | None = ...,
        original_rules: _abc.Iterable[Global___NameServer.OriginalRule] | None = ...,
        query_strategy: Global___QueryStrategy.ValueType = ...,
        actPrior: _builtins.bool = ...,
        tag: _builtins.str = ...,
        timeoutMs: _builtins.int = ...,
        disableCache: _builtins.bool | None = ...,
        serveStale: _builtins.bool | None = ...,
        serveExpiredTTL: _builtins.int | None = ...,
        finalQuery: _builtins.bool = ...,
        unexpected_geoip: _abc.Iterable[_config_pb2.GeoIP] | None = ...,
        actUnprior: _builtins.bool = ...,
        policyID: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_disableCache", b"_disableCache", "_serveExpiredTTL", b"_serveExpiredTTL", "_serveStale", b"_serveStale", "address", b"address", "disableCache", b"disableCache", "serveExpiredTTL", b"serveExpiredTTL", "serveStale", b"serveStale"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_disableCache", b"_disableCache", "_serveExpiredTTL", b"_serveExpiredTTL", "_serveStale", b"_serveStale", "actPrior", b"actPrior", "actUnprior", b"actUnprior", "address", b"address", "client_ip", b"client_ip", "disableCache", b"disableCache", "expected_geoip", b"expected_geoip", "finalQuery", b"finalQuery", "original_rules", b"original_rules", "policyID", b"policyID", "prioritized_domain", b"prioritized_domain", "query_strategy", b"query_strategy", "serveExpiredTTL", b"serveExpiredTTL", "serveStale", b"serveStale", "skipFallback", b"skipFallback", "tag", b"tag", "timeoutMs", b"timeoutMs", "unexpected_geoip", b"unexpected_geoip"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__disableCache: _TypeAlias = _typing.Literal["disableCache"]  # noqa: Y015
    _WhichOneofArgType__disableCache: _TypeAlias = _typing.Literal["_disableCache", b"_disableCache"]  # noqa: Y015
    _WhichOneofReturnType__serveExpiredTTL: _TypeAlias = _typing.Literal["serveExpiredTTL"]  # noqa: Y015
    _WhichOneofArgType__serveExpiredTTL: _TypeAlias = _typing.Literal["_serveExpiredTTL", b"_serveExpiredTTL"]  # noqa: Y015
    _WhichOneofReturnType__serveStale: _TypeAlias = _typing.Literal["serveStale"]  # noqa: Y015
    _WhichOneofArgType__serveStale: _TypeAlias = _typing.Literal["_serveStale", b"_serveStale"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__disableCache) -> _WhichOneofReturnType__disableCache | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__serveExpiredTTL) -> _WhichOneofReturnType__serveExpiredTTL | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__serveStale) -> _WhichOneofReturnType__serveStale | None: ...

Global___NameServer: _TypeAlias = NameServer  # noqa: Y015

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class HostMapping(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TYPE_FIELD_NUMBER: _builtins.int
        DOMAIN_FIELD_NUMBER: _builtins.int
        IP_FIELD_NUMBER: _builtins.int
        PROXIED_DOMAIN_FIELD_NUMBER: _builtins.int
        type: Global___DomainMatchingType.ValueType
        domain: _builtins.str
        proxied_domain: _builtins.str
        """ProxiedDomain indicates the mapped domain has the same IP address on this
        domain. Xray will use this domain for IP queries.
        """
        @_builtins.property
        def ip(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
        def __init__(
            self,
            *,
            type: Global___DomainMatchingType.ValueType = ...,
            domain: _builtins.str = ...,
            ip: _abc.Iterable[_builtins.bytes] | None = ...,
            proxied_domain: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["domain", b"domain", "ip", b"ip", "proxied_domain", b"proxied_domain", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    NAME_SERVER_FIELD_NUMBER: _builtins.int
    CLIENT_IP_FIELD_NUMBER: _builtins.int
    STATIC_HOSTS_FIELD_NUMBER: _builtins.int
    TAG_FIELD_NUMBER: _builtins.int
    DISABLECACHE_FIELD_NUMBER: _builtins.int
    SERVESTALE_FIELD_NUMBER: _builtins.int
    SERVEEXPIREDTTL_FIELD_NUMBER: _builtins.int
    QUERY_STRATEGY_FIELD_NUMBER: _builtins.int
    DISABLEFALLBACK_FIELD_NUMBER: _builtins.int
    DISABLEFALLBACKIFMATCH_FIELD_NUMBER: _builtins.int
    ENABLEPARALLELQUERY_FIELD_NUMBER: _builtins.int
    client_ip: _builtins.bytes
    """Client IP for EDNS client subnet. Must be 4 bytes (IPv4) or 16 bytes
    (IPv6).
    """
    tag: _builtins.str
    """Tag is the inbound tag of DNS client."""
    disableCache: _builtins.bool
    """DisableCache disables DNS cache"""
    serveStale: _builtins.bool
    serveExpiredTTL: _builtins.int
    query_strategy: Global___QueryStrategy.ValueType
    disableFallback: _builtins.bool
    disableFallbackIfMatch: _builtins.bool
    enableParallelQuery: _builtins.bool
    @_builtins.property
    def name_server(self) -> _containers.RepeatedCompositeFieldContainer[Global___NameServer]:
        """NameServer list used by this DNS client.
        A special value 'localhost' as a domain address can be set to use DNS on local system.
        """

    @_builtins.property
    def static_hosts(self) -> _containers.RepeatedCompositeFieldContainer[Global___Config.HostMapping]: ...
    def __init__(
        self,
        *,
        name_server: _abc.Iterable[Global___NameServer] | None = ...,
        client_ip: _builtins.bytes = ...,
        static_hosts: _abc.Iterable[Global___Config.HostMapping] | None = ...,
        tag: _builtins.str = ...,
        disableCache: _builtins.bool = ...,
        serveStale: _builtins.bool = ...,
        serveExpiredTTL: _builtins.int = ...,
        query_strategy: Global___QueryStrategy.ValueType = ...,
        disableFallback: _builtins.bool = ...,
        disableFallbackIfMatch: _builtins.bool = ...,
        enableParallelQuery: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_ip", b"client_ip", "disableCache", b"disableCache", "disableFallback", b"disableFallback", "disableFallbackIfMatch", b"disableFallbackIfMatch", "enableParallelQuery", b"enableParallelQuery", "name_server", b"name_server", "query_strategy", b"query_strategy", "serveExpiredTTL", b"serveExpiredTTL", "serveStale", b"serveStale", "static_hosts", b"static_hosts", "tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
