"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from common.net import address_pb2 as _address_pb2
from common.net import port_pb2 as _port_pb2
from common.serial import typed_message_pb2 as _typed_message_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from transport.internet import config_pb2 as _config_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class InboundConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___InboundConfig: _TypeAlias = InboundConfig  # noqa: Y015

@_typing.final
class SniffingConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENABLED_FIELD_NUMBER: _builtins.int
    DESTINATION_OVERRIDE_FIELD_NUMBER: _builtins.int
    DOMAINS_EXCLUDED_FIELD_NUMBER: _builtins.int
    METADATA_ONLY_FIELD_NUMBER: _builtins.int
    ROUTE_ONLY_FIELD_NUMBER: _builtins.int
    enabled: _builtins.bool
    """Whether or not to enable content sniffing on an inbound connection."""
    metadata_only: _builtins.bool
    """Whether should only try to sniff metadata without waiting for client input.
    Can be used to support SMTP like protocol where server send the first
    message.
    """
    route_only: _builtins.bool
    @_builtins.property
    def destination_override(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Override target destination if sniff'ed protocol is in the given list.
        Supported values are "http", "tls", "fakedns".
        """

    @_builtins.property
    def domains_excluded(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        enabled: _builtins.bool = ...,
        destination_override: _abc.Iterable[_builtins.str] | None = ...,
        domains_excluded: _abc.Iterable[_builtins.str] | None = ...,
        metadata_only: _builtins.bool = ...,
        route_only: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["destination_override", b"destination_override", "domains_excluded", b"domains_excluded", "enabled", b"enabled", "metadata_only", b"metadata_only", "route_only", b"route_only"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SniffingConfig: _TypeAlias = SniffingConfig  # noqa: Y015

@_typing.final
class ReceiverConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PORT_LIST_FIELD_NUMBER: _builtins.int
    LISTEN_FIELD_NUMBER: _builtins.int
    STREAM_SETTINGS_FIELD_NUMBER: _builtins.int
    RECEIVE_ORIGINAL_DESTINATION_FIELD_NUMBER: _builtins.int
    SNIFFING_SETTINGS_FIELD_NUMBER: _builtins.int
    receive_original_destination: _builtins.bool
    @_builtins.property
    def port_list(self) -> _port_pb2.PortList:
        """PortList specifies the ports which the Receiver should listen on."""

    @_builtins.property
    def listen(self) -> _address_pb2.IPOrDomain:
        """Listen specifies the IP address that the Receiver should listen on."""

    @_builtins.property
    def stream_settings(self) -> _config_pb2.StreamConfig: ...
    @_builtins.property
    def sniffing_settings(self) -> Global___SniffingConfig: ...
    def __init__(
        self,
        *,
        port_list: _port_pb2.PortList | None = ...,
        listen: _address_pb2.IPOrDomain | None = ...,
        stream_settings: _config_pb2.StreamConfig | None = ...,
        receive_original_destination: _builtins.bool = ...,
        sniffing_settings: Global___SniffingConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["listen", b"listen", "port_list", b"port_list", "sniffing_settings", b"sniffing_settings", "stream_settings", b"stream_settings"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["listen", b"listen", "port_list", b"port_list", "receive_original_destination", b"receive_original_destination", "sniffing_settings", b"sniffing_settings", "stream_settings", b"stream_settings"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReceiverConfig: _TypeAlias = ReceiverConfig  # noqa: Y015

@_typing.final
class InboundHandlerConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    RECEIVER_SETTINGS_FIELD_NUMBER: _builtins.int
    PROXY_SETTINGS_FIELD_NUMBER: _builtins.int
    tag: _builtins.str
    @_builtins.property
    def receiver_settings(self) -> _typed_message_pb2.TypedMessage: ...
    @_builtins.property
    def proxy_settings(self) -> _typed_message_pb2.TypedMessage: ...
    def __init__(
        self,
        *,
        tag: _builtins.str = ...,
        receiver_settings: _typed_message_pb2.TypedMessage | None = ...,
        proxy_settings: _typed_message_pb2.TypedMessage | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["proxy_settings", b"proxy_settings", "receiver_settings", b"receiver_settings"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["proxy_settings", b"proxy_settings", "receiver_settings", b"receiver_settings", "tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___InboundHandlerConfig: _TypeAlias = InboundHandlerConfig  # noqa: Y015

@_typing.final
class OutboundConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___OutboundConfig: _TypeAlias = OutboundConfig  # noqa: Y015

@_typing.final
class SenderConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIA_FIELD_NUMBER: _builtins.int
    STREAM_SETTINGS_FIELD_NUMBER: _builtins.int
    PROXY_SETTINGS_FIELD_NUMBER: _builtins.int
    MULTIPLEX_SETTINGS_FIELD_NUMBER: _builtins.int
    VIA_CIDR_FIELD_NUMBER: _builtins.int
    TARGET_STRATEGY_FIELD_NUMBER: _builtins.int
    via_cidr: _builtins.str
    target_strategy: _config_pb2.DomainStrategy.ValueType
    @_builtins.property
    def via(self) -> _address_pb2.IPOrDomain:
        """Send traffic through the given IP. Only IP is allowed."""

    @_builtins.property
    def stream_settings(self) -> _config_pb2.StreamConfig: ...
    @_builtins.property
    def proxy_settings(self) -> _config_pb2.ProxyConfig: ...
    @_builtins.property
    def multiplex_settings(self) -> Global___MultiplexingConfig: ...
    def __init__(
        self,
        *,
        via: _address_pb2.IPOrDomain | None = ...,
        stream_settings: _config_pb2.StreamConfig | None = ...,
        proxy_settings: _config_pb2.ProxyConfig | None = ...,
        multiplex_settings: Global___MultiplexingConfig | None = ...,
        via_cidr: _builtins.str = ...,
        target_strategy: _config_pb2.DomainStrategy.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["multiplex_settings", b"multiplex_settings", "proxy_settings", b"proxy_settings", "stream_settings", b"stream_settings", "via", b"via"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["multiplex_settings", b"multiplex_settings", "proxy_settings", b"proxy_settings", "stream_settings", b"stream_settings", "target_strategy", b"target_strategy", "via", b"via", "via_cidr", b"via_cidr"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SenderConfig: _TypeAlias = SenderConfig  # noqa: Y015

@_typing.final
class MultiplexingConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENABLED_FIELD_NUMBER: _builtins.int
    CONCURRENCY_FIELD_NUMBER: _builtins.int
    XUDPCONCURRENCY_FIELD_NUMBER: _builtins.int
    XUDPPROXYUDP443_FIELD_NUMBER: _builtins.int
    enabled: _builtins.bool
    """Whether or not Mux is enabled."""
    concurrency: _builtins.int
    """Max number of concurrent connections that one Mux connection can handle."""
    xudpConcurrency: _builtins.int
    """Transport XUDP in another Mux."""
    xudpProxyUDP443: _builtins.str
    """"reject" (default), "allow" or "skip"."""
    def __init__(
        self,
        *,
        enabled: _builtins.bool = ...,
        concurrency: _builtins.int = ...,
        xudpConcurrency: _builtins.int = ...,
        xudpProxyUDP443: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["concurrency", b"concurrency", "enabled", b"enabled", "xudpConcurrency", b"xudpConcurrency", "xudpProxyUDP443", b"xudpProxyUDP443"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MultiplexingConfig: _TypeAlias = MultiplexingConfig  # noqa: Y015
