"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Control(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _State:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Control._State.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        ACTIVE: Control._State.ValueType  # 0
        DRAIN: Control._State.ValueType  # 1

    class State(_State, metaclass=_StateEnumTypeWrapper): ...
    ACTIVE: Control.State.ValueType  # 0
    DRAIN: Control.State.ValueType  # 1

    STATE_FIELD_NUMBER: _builtins.int
    RANDOM_FIELD_NUMBER: _builtins.int
    state: Global___Control.State.ValueType
    random: _builtins.bytes
    def __init__(
        self,
        *,
        state: Global___Control.State.ValueType = ...,
        random: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["random", b"random", "state", b"state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Control: _TypeAlias = Control  # noqa: Y015

@_typing.final
class BridgeConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    DOMAIN_FIELD_NUMBER: _builtins.int
    tag: _builtins.str
    domain: _builtins.str
    def __init__(
        self,
        *,
        tag: _builtins.str = ...,
        domain: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["domain", b"domain", "tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BridgeConfig: _TypeAlias = BridgeConfig  # noqa: Y015

@_typing.final
class PortalConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    DOMAIN_FIELD_NUMBER: _builtins.int
    tag: _builtins.str
    domain: _builtins.str
    def __init__(
        self,
        *,
        tag: _builtins.str = ...,
        domain: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["domain", b"domain", "tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PortalConfig: _TypeAlias = PortalConfig  # noqa: Y015

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BRIDGE_CONFIG_FIELD_NUMBER: _builtins.int
    PORTAL_CONFIG_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def bridge_config(self) -> _containers.RepeatedCompositeFieldContainer[Global___BridgeConfig]: ...
    @_builtins.property
    def portal_config(self) -> _containers.RepeatedCompositeFieldContainer[Global___PortalConfig]: ...
    def __init__(
        self,
        *,
        bridge_config: _abc.Iterable[Global___BridgeConfig] | None = ...,
        portal_config: _abc.Iterable[Global___PortalConfig] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bridge_config", b"bridge_config", "portal_config", b"portal_config"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
