"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from common.serial import typed_message_pb2 as _typed_message_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Config(_message.Message):
    """Config is the settings for Commander."""

    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    LISTEN_FIELD_NUMBER: _builtins.int
    SERVICE_FIELD_NUMBER: _builtins.int
    tag: _builtins.str
    """Tag of the outbound handler that handles grpc connections."""
    listen: _builtins.str
    """Network address of commander grpc service."""
    @_builtins.property
    def service(self) -> _containers.RepeatedCompositeFieldContainer[_typed_message_pb2.TypedMessage]:
        """Services that supported by this server. All services must implement Service
        interface.
        """

    def __init__(
        self,
        *,
        tag: _builtins.str = ...,
        listen: _builtins.str = ...,
        service: _abc.Iterable[_typed_message_pb2.TypedMessage] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["listen", b"listen", "service", b"service", "tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015

@_typing.final
class ReflectionConfig(_message.Message):
    """ReflectionConfig is the placeholder config for ReflectionService."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReflectionConfig: _TypeAlias = ReflectionConfig  # noqa: Y015
