"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from app.proxyman import config_pb2 as _config_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Reverse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    SNIFFING_FIELD_NUMBER: _builtins.int
    tag: _builtins.str
    @_builtins.property
    def sniffing(self) -> _config_pb2.SniffingConfig: ...
    def __init__(
        self,
        *,
        tag: _builtins.str = ...,
        sniffing: _config_pb2.SniffingConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["sniffing", b"sniffing"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sniffing", b"sniffing", "tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Reverse: _TypeAlias = Reverse  # noqa: Y015

@_typing.final
class Account(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    FLOW_FIELD_NUMBER: _builtins.int
    ENCRYPTION_FIELD_NUMBER: _builtins.int
    XORMODE_FIELD_NUMBER: _builtins.int
    SECONDS_FIELD_NUMBER: _builtins.int
    PADDING_FIELD_NUMBER: _builtins.int
    REVERSE_FIELD_NUMBER: _builtins.int
    TESTPRE_FIELD_NUMBER: _builtins.int
    TESTSEED_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """ID of the account, in the form of a UUID, e.g., "66ad4540-b58c-4ad2-9926-ea63445a9b57"."""
    flow: _builtins.str
    """Flow settings. May be "xtls-rprx-vision"."""
    encryption: _builtins.str
    xorMode: _builtins.int
    seconds: _builtins.int
    padding: _builtins.str
    testpre: _builtins.int
    @_builtins.property
    def reverse(self) -> Global___Reverse: ...
    @_builtins.property
    def testseed(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        flow: _builtins.str = ...,
        encryption: _builtins.str = ...,
        xorMode: _builtins.int = ...,
        seconds: _builtins.int = ...,
        padding: _builtins.str = ...,
        reverse: Global___Reverse | None = ...,
        testpre: _builtins.int = ...,
        testseed: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["reverse", b"reverse"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["encryption", b"encryption", "flow", b"flow", "id", b"id", "padding", b"padding", "reverse", b"reverse", "seconds", b"seconds", "testpre", b"testpre", "testseed", b"testseed", "xorMode", b"xorMode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Account: _TypeAlias = Account  # noqa: Y015
