# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/vless/account.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'proxy/vless/account.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proxyman import config_pb2 as app_dot_proxyman_dot_config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proxy/vless/account.proto\x12\x10xray.proxy.vless\x1a\x19\x61pp/proxyman/config.proto\"K\n\x07Reverse\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x33\n\x08sniffing\x18\x02 \x01(\x0b\x32!.xray.app.proxyman.SniffingConfig\"\xb9\x01\n\x07\x41\x63\x63ount\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x66low\x18\x02 \x01(\t\x12\x12\n\nencryption\x18\x03 \x01(\t\x12\x0f\n\x07xorMode\x18\x04 \x01(\r\x12\x0f\n\x07seconds\x18\x05 \x01(\r\x12\x0f\n\x07padding\x18\x06 \x01(\t\x12*\n\x07reverse\x18\x07 \x01(\x0b\x32\x19.xray.proxy.vless.Reverse\x12\x0f\n\x07testpre\x18\x08 \x01(\r\x12\x10\n\x08testseed\x18\t \x03(\rBR\n\x14\x63om.xray.proxy.vlessP\x01Z%github.com/xtls/xray-core/proxy/vless\xaa\x02\x10Xray.Proxy.Vlessb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy.vless.account_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.xray.proxy.vlessP\001Z%github.com/xtls/xray-core/proxy/vless\252\002\020Xray.Proxy.Vless'
  _globals['_REVERSE']._serialized_start=74
  _globals['_REVERSE']._serialized_end=149
  _globals['_ACCOUNT']._serialized_start=152
  _globals['_ACCOUNT']._serialized_end=337
# @@protoc_insertion_point(module_scope)
