"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ObservationResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATUS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def status(self) -> _containers.RepeatedCompositeFieldContainer[Global___OutboundStatus]: ...
    def __init__(
        self,
        *,
        status: _abc.Iterable[Global___OutboundStatus] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ObservationResult: _TypeAlias = ObservationResult  # noqa: Y015

@_typing.final
class HealthPingMeasurementResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ALL_FIELD_NUMBER: _builtins.int
    FAIL_FIELD_NUMBER: _builtins.int
    DEVIATION_FIELD_NUMBER: _builtins.int
    AVERAGE_FIELD_NUMBER: _builtins.int
    MAX_FIELD_NUMBER: _builtins.int
    MIN_FIELD_NUMBER: _builtins.int
    all: _builtins.int
    fail: _builtins.int
    deviation: _builtins.int
    average: _builtins.int
    max: _builtins.int
    min: _builtins.int
    def __init__(
        self,
        *,
        all: _builtins.int = ...,
        fail: _builtins.int = ...,
        deviation: _builtins.int = ...,
        average: _builtins.int = ...,
        max: _builtins.int = ...,
        min: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["all", b"all", "average", b"average", "deviation", b"deviation", "fail", b"fail", "max", b"max", "min", b"min"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HealthPingMeasurementResult: _TypeAlias = HealthPingMeasurementResult  # noqa: Y015

@_typing.final
class OutboundStatus(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ALIVE_FIELD_NUMBER: _builtins.int
    DELAY_FIELD_NUMBER: _builtins.int
    LAST_ERROR_REASON_FIELD_NUMBER: _builtins.int
    OUTBOUND_TAG_FIELD_NUMBER: _builtins.int
    LAST_SEEN_TIME_FIELD_NUMBER: _builtins.int
    LAST_TRY_TIME_FIELD_NUMBER: _builtins.int
    HEALTH_PING_FIELD_NUMBER: _builtins.int
    alive: _builtins.bool
    """@Document Whether this outbound is usable
    @Restriction ReadOnlyForUser
    """
    delay: _builtins.int
    """@Document The time for probe request to finish.
    @Type time.ms
    @Restriction ReadOnlyForUser
    """
    last_error_reason: _builtins.str
    """@Document The last error caused this outbound failed to relay probe request
    @Restriction NotMachineReadable
    """
    outbound_tag: _builtins.str
    """@Document The outbound tag for this Server
    @Type id.outboundTag
    """
    last_seen_time: _builtins.int
    """@Document The time this outbound is known to be alive
    @Type id.outboundTag
    """
    last_try_time: _builtins.int
    """@Document The time this outbound is tried
    @Type id.outboundTag
    """
    @_builtins.property
    def health_ping(self) -> Global___HealthPingMeasurementResult: ...
    def __init__(
        self,
        *,
        alive: _builtins.bool = ...,
        delay: _builtins.int = ...,
        last_error_reason: _builtins.str = ...,
        outbound_tag: _builtins.str = ...,
        last_seen_time: _builtins.int = ...,
        last_try_time: _builtins.int = ...,
        health_ping: Global___HealthPingMeasurementResult | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["health_ping", b"health_ping"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["alive", b"alive", "delay", b"delay", "health_ping", b"health_ping", "last_error_reason", b"last_error_reason", "last_seen_time", b"last_seen_time", "last_try_time", b"last_try_time", "outbound_tag", b"outbound_tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___OutboundStatus: _TypeAlias = OutboundStatus  # noqa: Y015

@_typing.final
class ProbeResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ALIVE_FIELD_NUMBER: _builtins.int
    DELAY_FIELD_NUMBER: _builtins.int
    LAST_ERROR_REASON_FIELD_NUMBER: _builtins.int
    alive: _builtins.bool
    """@Document Whether this outbound is usable
    @Restriction ReadOnlyForUser
    """
    delay: _builtins.int
    """@Document The time for probe request to finish.
    @Type time.ms
    @Restriction ReadOnlyForUser
    """
    last_error_reason: _builtins.str
    """@Document The error caused this outbound failed to relay probe request
    @Restriction NotMachineReadable
    """
    def __init__(
        self,
        *,
        alive: _builtins.bool = ...,
        delay: _builtins.int = ...,
        last_error_reason: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["alive", b"alive", "delay", b"delay", "last_error_reason", b"last_error_reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProbeResult: _TypeAlias = ProbeResult  # noqa: Y015

@_typing.final
class Intensity(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROBE_INTERVAL_FIELD_NUMBER: _builtins.int
    probe_interval: _builtins.int
    """@Document The time interval for a probe request in ms.
    @Type time.ms
    """
    def __init__(
        self,
        *,
        probe_interval: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["probe_interval", b"probe_interval"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Intensity: _TypeAlias = Intensity  # noqa: Y015

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUBJECT_SELECTOR_FIELD_NUMBER: _builtins.int
    PROBE_URL_FIELD_NUMBER: _builtins.int
    PROBE_INTERVAL_FIELD_NUMBER: _builtins.int
    ENABLE_CONCURRENCY_FIELD_NUMBER: _builtins.int
    probe_url: _builtins.str
    probe_interval: _builtins.int
    enable_concurrency: _builtins.bool
    @_builtins.property
    def subject_selector(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """@Document The selectors for outbound under observation"""

    def __init__(
        self,
        *,
        subject_selector: _abc.Iterable[_builtins.str] | None = ...,
        probe_url: _builtins.str = ...,
        probe_interval: _builtins.int = ...,
        enable_concurrency: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enable_concurrency", b"enable_concurrency", "probe_interval", b"probe_interval", "probe_url", b"probe_url", "subject_selector", b"subject_selector"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
