"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from common.serial import typed_message_pb2 as _typed_message_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Config(_message.Message):
    """Config is the master config of Xray. Xray takes this config as input and
    functions accordingly.
    """

    DESCRIPTOR: _descriptor.Descriptor

    INBOUND_FIELD_NUMBER: _builtins.int
    OUTBOUND_FIELD_NUMBER: _builtins.int
    APP_FIELD_NUMBER: _builtins.int
    EXTENSION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def inbound(self) -> _containers.RepeatedCompositeFieldContainer[Global___InboundHandlerConfig]:
        """Inbound handler configurations. Must have at least one item."""

    @_builtins.property
    def outbound(self) -> _containers.RepeatedCompositeFieldContainer[Global___OutboundHandlerConfig]:
        """Outbound handler configurations. Must have at least one item. The first
        item is used as default for routing.
        """

    @_builtins.property
    def app(self) -> _containers.RepeatedCompositeFieldContainer[_typed_message_pb2.TypedMessage]:
        """App is for configurations of all features in Xray. A feature must
        implement the Feature interface, and its config type must be registered
        through common.RegisterConfig.
        """

    @_builtins.property
    def extension(self) -> _containers.RepeatedCompositeFieldContainer[_typed_message_pb2.TypedMessage]:
        """Configuration for extensions. The config may not work if corresponding
        extension is not loaded into Xray. Xray will ignore such config during
        initialization.
        """

    def __init__(
        self,
        *,
        inbound: _abc.Iterable[Global___InboundHandlerConfig] | None = ...,
        outbound: _abc.Iterable[Global___OutboundHandlerConfig] | None = ...,
        app: _abc.Iterable[_typed_message_pb2.TypedMessage] | None = ...,
        extension: _abc.Iterable[_typed_message_pb2.TypedMessage] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app", b"app", "extension", b"extension", "inbound", b"inbound", "outbound", b"outbound"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015

@_typing.final
class InboundHandlerConfig(_message.Message):
    """InboundHandlerConfig is the configuration for inbound handler."""

    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    RECEIVER_SETTINGS_FIELD_NUMBER: _builtins.int
    PROXY_SETTINGS_FIELD_NUMBER: _builtins.int
    tag: _builtins.str
    """Tag of the inbound handler. The tag must be unique among all inbound
    handlers
    """
    @_builtins.property
    def receiver_settings(self) -> _typed_message_pb2.TypedMessage:
        """Settings for how this inbound proxy is handled."""

    @_builtins.property
    def proxy_settings(self) -> _typed_message_pb2.TypedMessage:
        """Settings for inbound proxy. Must be one of the inbound proxies."""

    def __init__(
        self,
        *,
        tag: _builtins.str = ...,
        receiver_settings: _typed_message_pb2.TypedMessage | None = ...,
        proxy_settings: _typed_message_pb2.TypedMessage | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["proxy_settings", b"proxy_settings", "receiver_settings", b"receiver_settings"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["proxy_settings", b"proxy_settings", "receiver_settings", b"receiver_settings", "tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___InboundHandlerConfig: _TypeAlias = InboundHandlerConfig  # noqa: Y015

@_typing.final
class OutboundHandlerConfig(_message.Message):
    """OutboundHandlerConfig is the configuration for outbound handler."""

    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    SENDER_SETTINGS_FIELD_NUMBER: _builtins.int
    PROXY_SETTINGS_FIELD_NUMBER: _builtins.int
    EXPIRE_FIELD_NUMBER: _builtins.int
    COMMENT_FIELD_NUMBER: _builtins.int
    tag: _builtins.str
    """Tag of this outbound handler."""
    expire: _builtins.int
    """If not zero, this outbound will be expired in seconds. Not used for now."""
    comment: _builtins.str
    """Comment of this outbound handler. Not used for now."""
    @_builtins.property
    def sender_settings(self) -> _typed_message_pb2.TypedMessage:
        """Settings for how to dial connection for this outbound handler."""

    @_builtins.property
    def proxy_settings(self) -> _typed_message_pb2.TypedMessage:
        """Settings for this outbound proxy. Must be one of the outbound proxies."""

    def __init__(
        self,
        *,
        tag: _builtins.str = ...,
        sender_settings: _typed_message_pb2.TypedMessage | None = ...,
        proxy_settings: _typed_message_pb2.TypedMessage | None = ...,
        expire: _builtins.int = ...,
        comment: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["proxy_settings", b"proxy_settings", "sender_settings", b"sender_settings"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["comment", b"comment", "expire", b"expire", "proxy_settings", b"proxy_settings", "sender_settings", b"sender_settings", "tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___OutboundHandlerConfig: _TypeAlias = OutboundHandlerConfig  # noqa: Y015
