"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Header(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """"Accept", "Cookie", etc"""
    @_builtins.property
    def value(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Each entry must be valid in one piece. Random entry will be chosen if
        multiple entries present.
        """

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        value: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Header: _TypeAlias = Header  # noqa: Y015

@_typing.final
class Version(_message.Message):
    """HTTP version. Default value "1.1"."""

    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.str
    def __init__(
        self,
        *,
        value: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Version: _TypeAlias = Version  # noqa: Y015

@_typing.final
class Method(_message.Message):
    """HTTP method. Default value "GET"."""

    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.str
    def __init__(
        self,
        *,
        value: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Method: _TypeAlias = Method  # noqa: Y015

@_typing.final
class RequestConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VERSION_FIELD_NUMBER: _builtins.int
    METHOD_FIELD_NUMBER: _builtins.int
    URI_FIELD_NUMBER: _builtins.int
    HEADER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def version(self) -> Global___Version:
        """Full HTTP version like "1.1"."""

    @_builtins.property
    def method(self) -> Global___Method:
        """GET, POST, CONNECT etc"""

    @_builtins.property
    def uri(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """URI like "/login.php" """

    @_builtins.property
    def header(self) -> _containers.RepeatedCompositeFieldContainer[Global___Header]: ...
    def __init__(
        self,
        *,
        version: Global___Version | None = ...,
        method: Global___Method | None = ...,
        uri: _abc.Iterable[_builtins.str] | None = ...,
        header: _abc.Iterable[Global___Header] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["method", b"method", "version", b"version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["header", b"header", "method", b"method", "uri", b"uri", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RequestConfig: _TypeAlias = RequestConfig  # noqa: Y015

@_typing.final
class Status(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    code: _builtins.str
    """Status code. Default "200"."""
    reason: _builtins.str
    """Statue reason. Default "OK"."""
    def __init__(
        self,
        *,
        code: _builtins.str = ...,
        reason: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "reason", b"reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Status: _TypeAlias = Status  # noqa: Y015

@_typing.final
class ResponseConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VERSION_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    HEADER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def version(self) -> Global___Version: ...
    @_builtins.property
    def status(self) -> Global___Status: ...
    @_builtins.property
    def header(self) -> _containers.RepeatedCompositeFieldContainer[Global___Header]: ...
    def __init__(
        self,
        *,
        version: Global___Version | None = ...,
        status: Global___Status | None = ...,
        header: _abc.Iterable[Global___Header] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["status", b"status", "version", b"version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["header", b"header", "status", b"status", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseConfig: _TypeAlias = ResponseConfig  # noqa: Y015

@_typing.final
class Config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_FIELD_NUMBER: _builtins.int
    RESPONSE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def request(self) -> Global___RequestConfig:
        """Settings for authenticating requests. If not set, client side will not send
        authentication header, and server side will bypass authentication.
        """

    @_builtins.property
    def response(self) -> Global___ResponseConfig:
        """Settings for authenticating responses. If not set, client side will bypass
        authentication, and server side will not send authentication header.
        """

    def __init__(
        self,
        *,
        request: Global___RequestConfig | None = ...,
        response: Global___ResponseConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["request", b"request", "response", b"response"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["request", b"request", "response", b"response"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Config: _TypeAlias = Config  # noqa: Y015
