# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/hysteria/config.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'proxy/hysteria/config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protocol import server_spec_pb2 as common_dot_protocol_dot_server__spec__pb2
from common.protocol import user_pb2 as common_dot_protocol_dot_user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproxy/hysteria/config.proto\x12\x13xray.proxy.hysteria\x1a!common/protocol/server_spec.proto\x1a\x1a\x63ommon/protocol/user.proto\"U\n\x0c\x43lientConfig\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x34\n\x06server\x18\x02 \x01(\x0b\x32$.xray.common.protocol.ServerEndpoint\"9\n\x0cServerConfig\x12)\n\x05users\x18\x01 \x03(\x0b\x32\x1a.xray.common.protocol.UserB[\n\x17\x63om.xray.proxy.hysteriaP\x01Z(github.com/xtls/xray-core/proxy/hysteria\xaa\x02\x13Xray.Proxy.Hysteriab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy.hysteria.config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.xray.proxy.hysteriaP\001Z(github.com/xtls/xray-core/proxy/hysteria\252\002\023Xray.Proxy.Hysteria'
  _globals['_CLIENTCONFIG']._serialized_start=115
  _globals['_CLIENTCONFIG']._serialized_end=200
  _globals['_SERVERCONFIG']._serialized_start=202
  _globals['_SERVERCONFIG']._serialized_end=259
# @@protoc_insertion_point(module_scope)
